### ISSUE TITLE
Commands not ready yet?

### ISSUE THREAD

**Issue by FlailoftheLord** [BentoBoxWorld/Challenges#100]
I'm using the latest builds from all the BentoBox addons, BSkyblock, Challenges, Levevls & Biomes.
 (As of Febuary 25)
![2019-02-25_18h30_25](https://user-images.githubusercontent.com/41513161/53376167-76bd3880-392b-11e9-8e06-b02bcf64396d.png)

I type /is challenges
And it tells me that the command is not ready yet
![2019-02-25_18h26_16](https://user-images.githubusercontent.com/41513161/53376082-38c01480-392b-11e9-895d-d756c12c0653.png)

**Comment by smmmadden** [comment]
confirmed - it was working previously when I was updating the Wiki pages.  Now it shows the same message as above.

**Comment by BONNe** [comment]
Cuz, admin must create challenges before users could run the command.
