### ISSUE TITLE
Challenge "Alchemist" has typos

### ISSUE THREAD

**Issue by akoldfart** [BentoBoxWorld/Challenges#102]
### Description
I have not tested all challenges but my players told me about Alchemist. In challenges.yml (default plugin generated file) section requiredItems has items with too many :::'s. Players are unable to complete challenge as is. Also there has been confusion about "INSTANT_" because there is no such thing as INSTANT_HEAL or INSTANT_DAMAGE. What worked was HEALING and HARMING. Please check and test. I got my file working after removing extra :::'s and heal and damage requirements.

#### Server / BentoBox information:
Spigot 1.13.2
BentoBox 1.3.1
Challenges 0.6.1

**Comment by thunderlight411** [comment]
problem still exist in bentobox 1.4 and Challanges 0.6.5

**Comment by BONNe** [comment]
Well, it is because noone has fixed it. 
And I doubt that it is necessary to do it, because ASB standard is outdated and should not be used.

**Comment by akoldfart** [comment]
Does that kinda make updating this addon pointless? Default file works fine if you guys just fix the obvious so we don't need to figure out what's wrong. If we need to create file ourself then I see what you're saying.

**Comment by BONNe** [comment]
Challenges.yml will be removed in 0.7.0 release completely.

There will be still the ability to import challenges from ASkyBlock standard, but this file will not be generated anymore.
