### ISSUE TITLE
Coop making challenges

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/Challenges#103]
### Description

Im not sure if this was fixed, but its better to duplicate, than not report.

On versions listed below its possible to make challenges that require blocks on island by being in coop, what should not be possible. 

#### Server / BentoBox information:
20.03 10:42:49 [Server] INFO Bentobox version: 1.1-SNAPSHOT
20.03 10:42:49 [Server] INFO Loaded Game Worlds:
20.03 10:42:49 [Server] INFO SkyBlock (SkyBlock)
20.03 10:42:49 [Server] INFO Loaded Add-Ons
20.03 10:42:49 [Server] INFO BSkyBlock 1.1-SNAPSHOT
20.03 10:42:49 [Server] INFO Challenges 0.3.1-SNAPSHOT
20.03 10:42:49 [Server] INFO Biomes 0.4.0
20.03 10:42:49 [Server] INFO WelcomeWarps 0.1.0-SNAPSHOT
20.03 10:42:49 [Server] INFO Level 1.1-SNAPSHOT

#### Expected behavior / Additional context
Block making blocks, level challenges on cooped islands

**Comment by BONNe** [comment]
Implemented in 0.6 version.
