### ISSUE TITLE
ERROR Could not pass event WorldSaveEvent to BentoBox v1.4.0

### ISSUE THREAD

**Issue by Audrerose** [BentoBoxWorld/Challenges#104]
#### Describe the bug

Each 5 minutes i got this message on my consol following with bunch of info. I put a link for screen below.  I just want to know how to fix that pls because this is make my server crash since a updated to 1.4.0

ERROR Could not pass event WorldSaveEvent to BentoBox v1.4.0

#### Steps to reproduce the behavior

I just put the last release of Bentobox and restarted my server and i started to get this error.

#### Screenshots and videos

[http://zupimages.net/viewer.php?id=19/14/fef9.png](url)

#### Server

 - OS: ** Linux Debian 8.11 **
 - Java version: ** 8 **

#### Plugins

```
AreaShop
bentobox-1.4.0
BottledExp2.2.5.0
Citizens-2.0.24-b1605
CoreProtect_2.14.2
Dynmap-3.0-beta-3-spigot
EssentialsX-2.16.0.34
EssentialsXAntiBuild-2.16.0.34
EssentialsXChat-2.16.0.34
EssentialsXProtect-2.16.0.34
EssentialsXSpawn-2.16.0.34
HealthBar
HolographicDisplays
Jobs4.9.5
Lift
MinePacks
MobCapture
Modern-LWC-2.1.2
Multiverse-Core-2.6.0
Multiverse-Portals-2.5.2-SNAPSHOT
nuvotifier-2.5.0
PermissionsEx-1.33.8
perworldinventory-kt-2.2.2
QuickShop-1.13-0.9.39-beta
Resurrection
RifleChairs
SignEditor
SkinsRestorer
TitleManager-2.1.3
TreeAssist-6.0.9
TreeTwerkReloaded
Vault
votifier-1.9
VotingPlugin
worldedit-bukkit-7.0.0-beta-04
WorldGuardExtraFlags
worldguard-legacy-7.0.0-beta-02

```

##### BentoBox and Addons

```
commands.bentobox.version.server
Bentobox version: [name]
Loaded Game Worlds:
BSkyBlock_world (BSkyBlock)
CaveBlock-world (CaveBlock)
Loaded Add-Ons
BSkyBlock 1.4.0
CaveBlock 1.4.0-#0
Challenges 0.6.5-SNAPSHOT-#145
Level 1.4.0
WelcomeWarps 0.1.0-SNAPSHOT

```

##### Configuration

 - Database: ** YAML **

**Comment by Audrerose** [comment]
Sorry but its not fixed and i have the last challenges addon you put here....

**Comment by BONNe** [comment]
0.7.0-SNAPSHOT-# 148?

**Comment by Audrerose** [comment]
Where i can find this snapshot?

**Comment by BONNe** [comment]
I rework SaveListener for challenges addon.
This should not happen anymore.
