### ISSUE TITLE
Thread Bump

### ISSUE THREAD

**Issue by Max05pl** [BentoBoxWorld/Challenges#106]
### Description
Ok hi so i have this issue when I go to the challenges gui and i click on a challenge that requires blocks near you then server crash 
Crash https://pastebin.com/b84TAbJ6

#### Steps to reproduce the behavior:
get server
install
then put my challenge into folder
open challenges gui
click on my challenge
see your server freeze

#### Server / BentoBox information:
biomes 0.4.1
bsykblock 1.4.1
challenges 0.6.5 snapshot-#145
level 0.2.0
bentobox version 4.0 ([name])
Java 8
linux (multicraft)
minecraft spigot 1.13.2

#### Screenshots / Server log
https://pastebin.com/b84TAbJ6 the crash
and one example challenge thats failing
https://pastebin.com/nafjwYRk

#### Expected behavior / Additional context
It should just work like intendet

**Comment by BONNe** [comment]
Search radius for challenge : 
`searchRadius: 50000`
Algorithm searches 50000 * 50000 * 255 blocks...
ofcorse it will crash.

**Comment by Poslovitch** [comment]
Maybe you should add a notice about that in the config? Or even limit it.
