### ISSUE TITLE
challenges import fine, /is challenges causes Nosuchmethod error

### ISSUE THREAD

**Issue by RealmportalMC** [BentoBoxWorld/Challenges#107]
### Description

Nosuch method error on /is challenges

internal error has occured. 

#### Steps to reproduce the behavior:

import default challenges.yml file.
restart server
type /is challenges
#### Server / BentoBox information:
https://timings.aikar.co/?id=75387c5ee6ec467ea74d33206a9d3c13

using: Bentobox 1.4.0 , Bskyblock 1.4.2
with challenges 0.6.1

#### Screenshots / Server log
https://pastebin.com/uAzWu9yi

#### Expected behavior / Additional context
the challenges menu should show.

**Comment by BONNe** [comment]
You see, 0.6.1 is not compatible with bentobox 1.4
You should use 0.6.5-snapshot from release tab

**Comment by RealmportalMC** [comment]
Ok thanks
