### ISSUE TITLE
Show title & subtitle after challenge completion

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#108]
#### Describe the solution you'd like us to implement.

- Player completes a challenge
- Player is shown both title and subtitle message that he has just completed it

Example: 
![Screenshot_2](https://user-images.githubusercontent.com/46493763/57020432-87d73e00-6c29-11e9-97d3-addd26f4e7f7.png)

#### Describe alternatives you've considered.

I did not consider any others, but if someone has some variation that would be more cool to see, I will ask him to comment below

#### Additional context

- Would be cool if it was toggleable in settings
- If challenge name is coloured, then it takes the color in subtitle as well
- If a challenge has long name, it would be hard for it to fit on the screen (Has to be mentioned as a note somewhere)

**Comment by BONNe** [comment]
Implemented in 160 build.
