### ISSUE TITLE
Remove entities on challenge complete is not working

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#118]
### Description
Entities are not being killed after I complete a challenge that requires them to be around me even if the **Remove Entities** feature is active

#### Steps to reproduce the behavior:
1. Create **Island type** challenge
2. Require a Cow x1 (as an example) in radius of 10
3. Set **Remove Entities** feature to Active
4. Spam complete the challenge until max times, because the entities are not being removed

#### Server / BentoBox information:
![Screenshot_2](https://user-images.githubusercontent.com/46493763/57657365-730c8a00-75db-11e9-91d6-fd90af0a4779.png)

#### Expected behavior / Additional context
- Kill entities if the option is active
- I also think I have noticed something weird if you try to require both block and entity to be completed, but it's weird - so not sure.

**Comment by BONNe** [comment]
Thanks for your testing...
I fixed this too.
