### ISSUE TITLE
Required money feature doesn't sets correctly

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#119]
### Description
Setting island level requirement shares value with money requirement option. Example:
If u set island level requirement to 75, money sets to 75 too.

#### Steps to reproduce the behavior:
1. Create "Other type" challenge
2. Set any value for island level requirement (Example: 75)
3. Check value of money requirement without changing it (It shows 75. Please note that only the display is wrong, it actually changes in database)
4. Try overwriting the money requirement by using it's own settings menu
5. It will not change

#### Server / BentoBox information:
![Screenshot_2](https://user-images.githubusercontent.com/46493763/57659830-12357f80-75e4-11e9-8882-3375f128f881.png)

#### Expected behavior / Additional context
- Have separate values for each settings and not share them
- Overwrite the money value if I set it individually

**Comment by BONNe** [comment]
```
name = this.user.getTranslation("challenges.gui.buttons.admin.required-money");
description = new ArrayList<>(2);
description.add(this.user.getTranslation("challenges.gui.descriptions.admin.required-money"));
description.add(this.user.getTranslation("challenges.gui.descriptions.current-value","[value]", Long.toString(this.challenge.getRequiredIslandLevel())));
```

yea... it could be copy paste error... crap :D
