### ISSUE TITLE
Island type challenges that require more blocks reset their req. list

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#120]
### Description
I created a challenge that requires:
1x Oak door, 1 torch (not wall), 1x furnace, 1 crafting table, 1 flower pot, 1 glass block and 1 bookshelf, and after I had completed the challenge, the requirement list of those blocks resets. If you open via GUI, it will be empty!

Tested more than once while trying to require: 
Glass x1 - no problem ||
Crafting x1 - no problem ||
Torch x1 - no problem ||
Oak door x1 - no problem ||
Furnace x1 - no problem ||
...
But when I put it all together (x1)  - Boom, deleted after completion :[

#### Steps to reproduce the behavior:
1. Create a block required challenge with all of above materials x1 (http://prntscr.com/np4a6d)
2. Place blocks
3. Complete challenge
4. Look at the requirement GUI, it's empty! :[

#### Server / BentoBox information:
![bbox v](https://user-images.githubusercontent.com/46493763/57814159-10e68d00-7773-11e9-9efa-0345e4b6b4cd.png)

#### Expected behavior / Additional context
No errors in console or such. It's weird that it happened twice with more blocks requires at once.
It was very annoying trying to find blocks more than one time to see if I missaw + to test, so I'm definitely hoping that I won't be doing it again.

**Comment by BONNe** [comment]
Fixed.
