### ISSUE TITLE
Multi-Selection for Block Required challenges

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#121]
#### Is your feature request related to a problem?
Present single-block adding to required list is based on:
1-click -> 1 item added + your **GUI closes**, so you have to open and spam click "Next" pages for every block you require and search for it in the list. It would be very easier if you'd at least continue where from where you stopped when you added the block.

#### Describe the solution you'd like us to implement.
- Toggle Multi-Selection
- Click blocks required for Island Type challenge
- Press "Add selected" (Lime_Stained_Glass_Pane)
- || Press "Cancel selection" (Red_Stained_Glass_Pane)

**Comment by BONNe** [comment]
Right click does not work?

**Comment by wellnesscookie** [comment]
Oh, I'm so dumb! 😆 
http://prntscr.com/npzt91, the text is so long that I didn't even try to read it, because it's in 1 line.
I thought it was something to multi-delete, but this makes sence now.

Than my feature request is to put a few "\n", to see the whole text. Sorry!

**Comment by BONNe** [comment]
Sorry, it looks like I forgot to implement it.
Now it you will be able to select multiple elements from Blocks and Entities GUI.

**Comment by wellnesscookie** [comment]
@BONNe btw, 200th build on CodeMC, cheers! 😁
