### ISSUE TITLE
Color codes count as letters in lore messages

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#122]
### Description
**Best through an example:**

**I want to set a reward message text to:**
|&7Dobićeš 1x Jaje &cP&9a&ep&da&9g&ba&6j&3a

**The display is actually:**
Dobices 1x Jaje
Papagaja (In new line)

- Screenshot provided below
- Even though it tehnically has enough space to fit, not sure if it can be fixed or it's how minecraft works

#### Server / BentoBox information:
![Screenshot_1](https://user-images.githubusercontent.com/46493763/58132590-f7858b00-7c21-11e9-8312-eb1bc81e8c36.png)

#### Screenshots / Server log
**An example:**
Blue outline is the spacen taken
Red outline is the free space

![Screenshot_2](https://user-images.githubusercontent.com/46493763/58132649-26036600-7c22-11e9-981b-0a19fc00744c.png)

**Proof that I'm right:**
![Screenshot_3](https://user-images.githubusercontent.com/46493763/58133139-6f07ea00-7c23-11e9-9fa0-59f1c658c1a2.png)

#### Expected behavior / Additional context
If it's possible, then don't count colorcodes as letters?

**Comment by BONNe** [comment]
You can change line lenght in config or via admin gui

**Comment by wellnesscookie** [comment]
Yes, but then the above lines that do not welcome that extra length will each have to contain | symbol, just so I can move the lines myself not to be very long.

**Comment by BONNe** [comment]
I checked it, and it is too complicated to count only valid characters in the current implementation.
And as there is an option to increase lore line length, and use own line splittings (with '|'), I will not implement this for now.
