### ISSUE TITLE
Saving reward/ description messages adds an extra | symbol each time

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#123]
### Description
Each time you press "Save" on a reward/ description message it will add an extra | (symbol for new line) at the end of the message. It's not a big deal, since it does not display extra empty lines in /c GUI, but only in Repeat Reward Message on a view overlook.

#### Steps to reproduce the behavior:
1. Write a Reward Message
2. Save it
3. Open the Reward Message and move your cursor on the paper **below** ( +1 | )
4. See picture:
![Screenshot_6](https://user-images.githubusercontent.com/46493763/58133649-a034ea00-7c24-11e9-9dcd-07a236d6144f.png)
5. Edit nothing
6. Save
7. Go to step **3.**

#### Server / BentoBox information:
Challenges build #200

#### Screenshots / Server log
- **It only displays here and nowhere else:**
![Screenshot_4](https://user-images.githubusercontent.com/46493763/58133719-d8d4c380-7c24-11e9-91eb-43ef94e94396.png)

#### Expected behavior / Additional context
Up to you if you find it worthy fixing.

**Comment by BONNe** [comment]
Fixed in the latest development branch.
