### ISSUE TITLE
Free repeatable challenges

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Challenges#125]
### Description
There are problems in the challenges.
You can complete the challenge without giving up the items that you want on any mission, and you can repeat it and get your rewards.

challenges-0.7.5-SNAPSHOT #246
Minecraft 1.14.2

**Comment by BONNe** [comment]
Please, can you provide more information, f.e. challenges file that is bugged?

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/58762657-af883180-855a-11e9-8d4b-ce17444ae88b.png)

I can always do a challenge when I don't have items.
And I can get the awards of that mission without limit.

**Comment by BONNe** [comment]
Fast question, are you in CREATIVE mode?

**Comment by BONNe** [comment]
Not a bug.
Players in Creative Mode have all items in Universe.
