### ISSUE TITLE
Add possibility of formatting variables 

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/Challenges#128]
#### Is your feature request related to a problem?

It is possible to change look of almost everything in chsllanges gui. The problem is that we can't change formatting of challenges names or required texts. Even if we change color on challenge file it backs to Italian, purple text. 
#### Describe the solution you'd like us to implement.

Adding to Lang file formatting of challenge name, challenge completed name, requirements

**Comment by BONNe** [comment]
![ColoursinGui](https://user-images.githubusercontent.com/1344358/59564563-ed07b700-9050-11e9-95ab-e90dfc3a7636.png)

All exist. You can edit any color and formatting you want.
Unfortunately, different parts can be edited in different places:
Challenge Description and name can be edited in each challenge.
Other parts need to be edited in lang file by adding formatting code in challenges.gui.descriptions, challenges.gui.challenge-description and challenges.gui.level-description.

**Comment by Kryniowesegryderiusz** [comment]
I know that Challenge Description and name can be edited in each challenge, but when im trying to do that it reverses to default colors :/

**Comment by BONNe** [comment]
This requires a bit of reformatting challenges message generation.
