### ISSUE TITLE
GUI Editor Lose Functionality After Anvil Text Editing

### ISSUE THREAD

**Issue by Jerethkhan** [BentoBoxWorld/Challenges#132]
When editing anything that uses the anvil UI to edit, finishing the edit and returning challenges GUI disables the menu functions. The menu simply acts as a chest allowing you to remove the items. This disrupts saving things (such as island level) as you can no longer click the save button.

Reproduce by using any editing tool (such as island level) then return to the Challenge Editor UI.

#### Server / BentoBox information:
Server: Paper 1.14.2 R-0.1
BentoBox: Version 1.5.1
BentoBox Plugins: Biomes 1.5.0.0, BSkyBlock 1.5.0, Challenges 0.7.5, Level 1.5.0, MagicCobblestoneGenerator 1.5.0.1

#### Screenshots / Server log
No output when the error occurs.

**Comment by BONNe** [comment]
@Poslovitch 
This is BentoBox issue.
I add 2 PullRequests. Choose one:
#761 or #762

**Comment by BONNe** [comment]
This issue is fixed in BentoBox 1.5.2-SNAPSHOT.
