### ISSUE TITLE
item-alias file for lore output

### ISSUE THREAD

**Issue by Jerethkhan** [BentoBoxWorld/Challenges#133]
#### Is your feature request related to a problem?
I like the Challenges feature that auto-populates item requirement and rewards in the description. It saves quite a bit of time from having to type it all out manually and removes human error. The issue is that the only option is to use internal item names. This becomes an issue with things like "LIGHT_BLUE_STAIND_GLASS_PANE - x12" as it's extremely long and causes carriage returns in the default lore length.

#### Describe the solution you'd like us to implement.
I'd like to see an "item-alias" file. This kind of file is used in several other mods. It would be the same format as the "Level" addon config.yml but with a name instead of a point value. 
For example:
"LIGHT_BLUE_STAINED_GLASS_PANE: Light Blue Pane"
In the game, in the lore box for the challenge, you would see "Light Blue Pane - x12" instead of the internal file name.

An alternative would be an option to toggle between ID and Name. This would remove some customization, but would still solve the problem.

#### Describe alternatives you've considered.
I've considered just turning off the auto-populate and manually entering every reward/requirement by hand. Two reasons I don't like that method is A) Time required and B) The amount of room for human error when dealing with hundreds of items over dozens of challenges. Long term it seems to make more sense to have an alias list already included.

#### Additional context
N/A

**Comment by BONNe** [comment]
So I already done something like that in other addon, but did not yet add this in here.
But it was planned :)
I do not like these names too :)

**Comment by BONNe** [comment]
Done in 1.0
