### ISSUE TITLE
Possibilty to disable "Auto-Lore"

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Challenges#134]
#### Is your feature request linked to a problem?
I want to make a personalized description but I have the description Auto Lore.
https://www.noelshack.com/2019-24-5-1560516517-2019-06-14-14-45-16.png
#### Describe the solution you want us to implement.
I read this number but that's not what I'm looking for:
https://github.com/BentoBoxWorld/Challenges/issues/133
So I'm asking you if you can add the ability to add a line in the configuration to disable automatic "Auto-Lore" (not the amount of completions of challenges)
As the old challenges system of ASkyBlock in fact.

**Comment by BONNe** [comment]
You can do it.
Read config.yml

**Comment by Typheonn** [comment]
Oh, i didn't pay attention, sry ^^'

Thanks for the answer.
