### ISSUE TITLE
Challenge content overflow display range

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Challenges#135]
I have a challenge content that requires 16 mushroom stews. Since the mushroom stew can't overlap, the content of this challenge is very large. It is so serious that the player can't display the complete challenge content. I hope to add a function to fix this problem (it will not overlap) But the same project is merged when the challenge content is displayed)

**Comment by BONNe** [comment]
oh yea... that could be an issue with unstackable items. 
I will add functionality to group them.

**Comment by BackWheel** [comment]
I think there is another place to improve, that is, to hide the prizes and content of the repetitive challenge when making the first challenge, to repeat the challenge and then display it and thus complete the challenge for the first time, so as to reduce the occurrence of such problems.

**Comment by BONNe** [comment]
It is planned to add the ability to increase requirements each next time :) so then users will not be able to see new requirements :(

**Comment by BONNe** [comment]
Implemented in Challenges-0.8.0-SNAPSHOT-#273.jar
