### ISSUE TITLE
Admin Command to Complete Challenge s

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Challenges#136]
Hi.
### Description
It is possible to add one command that allow admins to complete challenges for other players pls ?

I know that the guy allow that but i want to make that auto so i need to have one command to that.

**Comment by BONNe** [comment]
there is.
for example, in skyblock: `/bsb challenges` allows to complete it with gui

**Comment by Typheonn** [comment]
I know this command. That what i wrote at the bottom.

That why i suggest to add a command less open a guy, as ASkyblock. Because sometimes, i need to give a lot of challenge to one player but automaticaly. But if i can't make /bsadmin completechallenge..., it's impossible :(

**Comment by BONNe** [comment]
Challenges-0.8.0-SNAPSHOT-#274.jar
