### ISSUE TITLE
Money Rewards Integer

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#140]
#### Is your feature request related to a problem?

The money reward for challenges is defined as an integer. This enables prices not lower than 1. or a multiplier of that and this is too rough. Especially for repeatable rewards, prices should be made with at least 1 decimal. This enables prices like 0.2 or 1.5 and expands the possibilities for better economy prices.

#### Describe the solution you'd like us to implement.

Define the money rewards as a number with (at least) 1 decimal.

#### Additional context

This was possible under Askyblock and was much appreciated.

**Comment by BONNe** [comment]
Done in 1.0
