### ISSUE TITLE
Reset Challenges from Console Commands

### ISSUE THREAD

**Issue by Jerethkhan** [BentoBoxWorld/Challenges#141]
#### Describe the solution you'd like us to implement.
ASB had a command to reset challenges. We used this to allow players who had completed all challenges to complete 1 last challenge that reset all of their challenges. They could then re-complete all the challenges over for the rewards (and in some cases updated rewards.) This command is not present in BSB removing that feature.

#### Describe alternatives you've considered.
There are no alternatives other than writing a completely new plugin or script.

**Comment by BONNe** [comment]
Implemented in [#277](https://ci.codemc.org/job/BentoBoxWorld/job/Challenges/277/).
