### ISSUE TITLE
Add requiredEntities to challenges.yml's file

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Challenges#142]
#### Is your feature request related to a problem?
Hi. Today i use the old file from ASkyBlock to create challenges because i prefer one file to config them than use a gui. But the "requiredEntities" is not possible. For example, when i make CHICKEN, it add the item and the entity to challenge requirement but i just want requirement. Can you do something pls ? Thx.

#### Describe alternatives you've considered.
Add the abibilty to make a line such as "requiredEntities" in the main config file (the wile which is use in command /bsadmin challenges import)

**Comment by Poslovitch** [comment]
The challenges.yml is only intended for ASB challenges import. It is otherwise completely stale and useless.
