### ISSUE TITLE
Admin command to reset challenge

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Challenges#145]
#### Is your feature request related to a problem?
As my first request, it is possible to add one command that allow admins to reset challenge for other players pls ?

I know that the guy allow that but i want to make that auto so i need to have one command to do that.

**Comment by BONNe** [comment]
Implemented in [Build #277](https://ci.codemc.org/job/BentoBoxWorld/job/Challenges/277/changes)
