### ISSUE TITLE
Order number integrer

### ISSUE THREAD

**Issue by Momonche** [BentoBoxWorld/Challenges#146]
#### Is your feature request related to a problem?
The order number max is 54
I have reached the limit of challenges

#### Describe the solution you'd like us to implement.
More number can be used in the order section

**Comment by BONNe** [comment]
Yea... I do not know why it is set to 54...
I think it is leftover from the old code.

**Comment by Momonche** [comment]
@BONNe I just realize, you are the dev of the Challenge addons !
You think you can add more order number soon ?

**Comment by BONNe** [comment]
Yea... 
I set max limitation to 9999, and will not increase it.

Implemented in [Build #280 ](https://ci.codemc.org/job/BentoBoxWorld/job/Challenges/280/)

**Comment by Momonche** [comment]
Thanks !
