### ISSUE TITLE
Translation description admin/players

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#148]
### Description

Challenges descriptions in the player gui display the command executed when the challenge is done. Most commands are a little complicated for players to understand and may possibly even reveal plugins.
It concerns (especially) the line:
challenges.gui.descriptions.command: '- [command]'

#### Steps to reproduce the behavior:

1. /is challenges
2. Optional: /bsb challenges

#### Expected behavior / Additional context

Ideally the player GUI lines should be separated from the admin GUI lines.
This way, the player locale lines can be altered or hidden (made empty) to simplify the player GUI but not the Admin GUI.

#### Server / BentoBox information:

Biomes 1.5.2.1-SNAPSHOT-b123 (ENABLED)
BSkyBlock 1.5.3-SNAPSHOT (ENABLED)
Challenges 0.8.0-SNAPSHOT-278 (ENABLED)
Level 1.5.1-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.1-SNAPSHOT (ENABLED)

#### Screenshots / Server log

![Screenshot_20190630_123055](https://user-images.githubusercontent.com/28690790/60395391-f275fe80-9b32-11e9-8f8c-c1958669c86e.png)

**Comment by BONNe** [comment]
This is more feature than a bug.
Separate Lore messages for a user and admin... it is doable, but definitely not a priority.

I will improve LORE GUI and admins will be able to enable/disable elements from it, but splitting will not be implemented for now.
