### ISSUE TITLE
challenges

### ISSUE THREAD

**Issue by ronc617** [BentoBoxWorld/Challenges#150]
having an issue with the challenges the level: seems to keep auto changing and putting a Capital letter in the config
![image](https://user-images.githubusercontent.com/36974241/60856166-3ec8da80-a1d4-11e9-9f4f-98720b84f189.png)

also small typo Cause
![image](https://user-images.githubusercontent.com/36974241/60856176-4ab49c80-a1d4-11e9-9ee2-87fad759e605.png)

![image](https://user-images.githubusercontent.com/36974241/60856057-e5f94200-a1d3-11e9-9522-f048d23ceb0b.png)

![image](https://user-images.githubusercontent.com/36974241/60856246-82bbdf80-a1d4-11e9-823a-f7a2f419622d.png)

**Comment by BONNe** [comment]
Can you provide your challenges and their level files?

**Comment by ronc617** [comment]
[bento.zip](https://github.com/BentoBoxWorld/Challenges/files/3379300/bento.zip)
attached is a zip of the challenge/challenge level folders
when i make the correction in the challenge file to make it lower case it changes it back and puts the capital letter producing the error shown previouls

**Comment by ronc617** [comment]
I took the server offline and made the changes to the challenge files and
started back up again. Seems like they might have held that time

**Comment by ronc617** [comment]
the changes i have made held after doing it while server was offline.
but it still looks like it would be an issue for new install as it was saving the Capital letter in the file

**Comment by BONNe** [comment]
Reworked Challenge Addon object ID generation. 
This issue should be solved in the latest development version.
