### ISSUE TITLE
Anvil Input broken

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#151]
### Description

I can't use the anvil input anymore. The GUI appears, but I can't type anything. This has been going on for about 2 weeks now.
Error appears on the console. See below.

#### Steps to reproduce the behavior:

1. Default server with paper 1.13.2
2. Minimum plugins and all latest BentoBox/Bskyblock/Challenges plugins
3. Start with a default configuration without any challenges
4. Execute /bsb challenges and try to make a new challenge
5. Alternatively try to edit an icon of an existing challenge

#### Server / BentoBox information:

Plugins (8): BentoBox, CMI, LuckPerms, PlaceholderAPI*, PlugMan, Vault*, WorldEdit, WorldGuard
Running PAPER 1.13.2.
BentoBox version: 1.6.0-SNAPSHOT-b1257
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.5.2.1-SNAPSHOT-b126 (ENABLED)
BSkyBlock 1.6.0-SNAPSHOT (ENABLED)
Challenges 0.8.0-SNAPSHOT-#280 (ENABLED)
Level 1.6.0-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)

#### Screenshots / Server log

https://pastebin.com/XYKA2WAT

#### Expected behavior / Additional context

This makes it quite hard to change anything on a running server.
The workaround is to shut down de server completely, then edit the files manually and start it again.

**Comment by BONNe** [comment]
AnvilInput removed
