### ISSUE TITLE
Please join more languages

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Challenges#152]
I have translated Chinese and Traditional Chinese into the Challenge component. I hope you can add these translations to the Challenge component. Thank you!
[lang.zip](https://github.com/BentoBoxWorld/Challenges/files/3389470/lang.zip)

**Comment by Hagb** [comment]
Thanks very much for your work! (In fact I'm also translating this file into Chinese version, but it isn't finished.) 
I suggest that you take a Push Request.

I'm translating file "default.json" into Chinese version too.

**Comment by BackWheel** [comment]
> 非常感谢您的工作！（事实上​​，我也将这个文件翻译成中文版，但还没有完成。）
> 
> 我正在将文件“default.json”翻译成中文版。

My English level is not particularly perfect. There may be some translation errors. You can also check if I have any translation errors.

**Comment by BackWheel** [comment]
@BONNe

**Comment by BONNe** [comment]
Files are added in the development build.
