### ISSUE TITLE
default.json translated into zh-CN

### ISSUE THREAD

**Issue by Hagb** [BentoBoxWorld/Challenges#153]
I'm translating default.json into Chinese version.

Is it possible or proper to push the translated default.json to this repository? (Maybe its filename will not be "default.json" but one with language code.)

And is it possible to import the translated default.json without modifying the jar file? (I replaced the default.json in the jar file and it worked well.)

**Comment by BONNe** [comment]
Will be possible with challenges library.
No ETA

**Comment by BackWheel** [comment]
Too clever, I still want to translate default.json, thank you very much for your work. @Hagb

**Comment by Hagb** [comment]
@BackWheel About 60% of translation has been completed.
约 60% 的翻译已经完成了。

**Comment by Hagb** [comment]
@BackWheel 
Translation has been completed, but before uploading it I still need to review.
（翻译完成，但上传前仍需审校。）

**Comment by BackWheel** [comment]
@Hagb Thanks

**Comment by Hagb** [comment]
@BackWheel 
I have completed translation and review. 
But I find something that may be bugs (#157) , and don't know what is meant by "some grind" (line 253)
我已经完成了翻译和审校。
但我发现一些疑似 bug 的东西 (#157)，并且不知道“some grind”啥意思 (第 253 行)。（或许是“折腾”的意思？）

[default_zh-CN.zip](https://github.com/BentoBoxWorld/Challenges/files/3397586/default_zh-CN.zip)

**Comment by Hagb** [comment]
@BONNe 
I think that maybe the translated default.json can be mentioned in README, which can avoid that somebody translates it (into zh-cn) again...

**Comment by BONNe** [comment]
In snapshot I added a new GUI, that will allow downloading different challenges libraries.
This is added as one of the values.
