### ISSUE TITLE
Challenges are not implemented in current world.

### ISSUE THREAD

**Issue by PEZ18** [BentoBoxWorld/Challenges#156]
### Description
There are no challenges present when typing /is challenges.
Standard user gets error message of "Challenges are not implemented in current world."
Admin gets empty GUI screen.

#### Steps to reproduce the behavior:
User tries command /is challenges but gets error listed above.
challenges as an admin:  /bsbadmin challenges then clicking on "complete user challenge icon" then select player head icon, but next screen is a bunch of blank boxes no icons no challenges of any sort. just a return door icon and a user list button icon is the only thing in that interface.
I installed latest spigot 1.14.3, also tried 1.14.2 but makes no difference. latest bentobox 1.5.3 and also tried 1.5.0 thinking that could be the issue but that made no difference...

When running the server and challenges addon for first time and so on, there is only a config.yml present but no challenges.yml file is ever created.

In previous version of bskyblock/challenges on minecraft 1.13.2 back in January, everything worked fine and there was a challenges.yml file present... I even tried to copy the old challenges.yml file to new latest builds but that did not work. I also tried to use a copy of my old server but update to all the latest bentobox/addons and spigot 1.14.3 but i get the same error message even though that challenges.yml file is there.

#### Server / BentoBox information:
bentobox 1.5.3 
bskyblock-1.5.0
Challenges-0.7.5

#### Screenshots / Server log
![console info](https://user-images.githubusercontent.com/45371402/61192473-71a61f00-a669-11e9-8664-aa5446cb8a7c.JPG)
![console-challenges](https://user-images.githubusercontent.com/45371402/61192474-723eb580-a669-11e9-81c2-5b220d219abe.JPG)
![spigot 2 and 3 tested](https://user-images.githubusercontent.com/45371402/61192475-723eb580-a669-11e9-90d8-64cbbc2428cd.JPG)
![addons folder](https://user-images.githubusercontent.com/45371402/61192476-723eb580-a669-11e9-86a3-008c4cf8a242.JPG)
![challenges folder](https://user-images.githubusercontent.com/45371402/61192477-723eb580-a669-11e9-9cef-a2924bd7504c.JPG)
![challenges-admin](https://user-images.githubusercontent.com/45371402/61192478-723eb580-a669-11e9-9849-5a836e25267e.png)
![challenges-user](https://user-images.githubusercontent.com/45371402/61192479-723eb580-a669-11e9-8764-3b171817b770.png)
![console addons loaded](https://user-images.githubusercontent.com/45371402/61192480-72d74c00-a669-11e9-8877-6f5ada41374e.JPG)

What am I doing wrong here? Is this challenges.yml no longer needed or is it located somewhere else now? is there no longer a default challenges.yml ? I am really lost on this one.
 I am really sorry if my bug report is sloppy, I am just an average user and new to all this.

**Comment by BONNe** [comment]
`challenges.yml` is not provided anymore as users were using it wrongly. It is just for importing ASkyBlock challenges, not for editing and creating new challenges.

There is default challenges, but they are not accessible in file format and for now, will not be. To implement default challenges you should use `/bsb challlenges` and in GUI click on `Import default challenges` button.

**Comment by PEZ18** [comment]
Thanks. Guess I overlooked that.
