### ISSUE TITLE
bugs in default.json ?

### ISSUE THREAD

**Issue by Hagb** [BentoBoxWorld/Challenges#157]
### Description

default.json : 
##### In the rewardText is saplings, but in the rewardItems is REDSTONE.
1490~1493
```
      "rewardText": "These saplings will help you to get more trees",
      "rewardItems": [
        "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 1631\n  type: REDSTONE\n  amount: 27\n"
],
```
1498~1503
```
      "repeatRewardText": "These saplings will help you to get more trees",
      "maxTimes": 100,
      "repeatExperienceReward": 5,
      "repeatItemReward": [
        "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 1631\n  type: REDSTONE\n  amount: 9\n"
],
```
##### I guess that this 'collest' is a spell error.
2049: ` "Use your mobfarm to collest mob drops"`
#### Steps to reproduce the behavior:

Just in default.json
#### Server / BentoBox information:

Challenges Beta 0.7.5 and also the Latest ( 2a30185 )

**Comment by Hagb** [comment]
##### Is 'Component' also a spell error?
2790,2791:
```
      "unlockMessage": "Congratulations - you unlocked the &dComponent level!",
      "rewardText": "Small reward for completing all Component challenges.",
```
But  2783,2784:
```
      "uniqueId": "competent",
      "friendlyName": "Competent",
```

**Comment by BONNe** [comment]
Yes it could be so... 
Thanks for check :) 
Will edit asap

**Comment by BONNe** [comment]
Fixed in latest development branch
