### ISSUE TITLE
Challenges being completed without items

### ISSUE THREAD

**Issue by LoXR** [BentoBoxWorld/Challenges#158]
### Description

Players have reported due to our recent opening of Skyblock, that you can complete the challenges without needing the required items. And upon completing them, they aren't given any rewards.
#### Steps to reproduce the behavior:

Haven't attempted to edit the config as we have left it default.
#### Server / BentoBox information:

BentoBox version 1.6.0-SNAPSHOT-b1275, BSKYBlock 1.6.0-SNAPSHOT, Challenges 0.8.0-SNAPSHOT, IslandFly 0.2.0, Level 1.6.0-SNAPSHOT, MagicCobblestoneGenerator 1.5.0.1
Database: SQL
Plugins (46): AuctionHouse, BentoBox, ChatManager, Citizens, CombatLogPro, CommandNPC*, CoreProtect, CrazyCrates, EditableSign, EnjinMinecraftPlugin, EpicHoppers, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, GambleBar*, GroupManager*, HolographicDisplays, IPWhitelist*, LagAssist, MineableSpawners, Panilla, PermissionTimer, PlaceholderAPI*, PlugMan*, ProtocolLib*, ProtocolSupport, ProtocolSupportLegacyChest, ScoreBoards*, ShopChest, SkinsRestorer, Spartan, SuperVanish, TAB, TigerReports*, UltimateKits, UltimateRepairing, UltimateStacker, Vault, VoidSpawn, Votifier, Voting*, VotingPlugin, WarningCategories*, WorldEdit, WorldGuard
#### Screenshots / Server log

No screenshots as we have the default config for Challenges.
Server startup log: https://pastebin.com/Dm9bLvht
#### Expected behavior / Additional context

Nothing else, but hoping there is a fix for this.

**Comment by LoXR** [comment]
Following up on this, one of the server admins said they imported some custom challenges over from ASkyblock, so this may be the reason of this happening.

**Comment by BONNe** [comment]
Some of ASkyBlock challenges cannot be completed as objects are not convertible. 
It is possible that a challenge is with empty items, and that is the reason why it is not removing any items or giving them. 
I suggest validating if that challenge is correct with in game gui.

**Comment by BONNe** [comment]
ASkyBlock importer removed as it was not working correctly.
