### ISSUE TITLE
Challenge content display is incomplete

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Challenges#159]
When the content of a challenge is too much, the information of the challenge often exceeds the display range of the screen, and the player cannot understand how to complete the challenge. How can I solve such a problem? Maybe you need a different display?

**Comment by BONNe** [comment]
Maybe you could show what you mean with it?

And you can modify Challenges/Levels descriptions in a config file.

**Comment by BackWheel** [comment]
I think I can make a Lore wrap to solve this problem.
