### ISSUE TITLE
Right click ChallengeGUI

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#163]
### Description

A (default) player (!) can right click on the challenge gui which is definitely not supposed to do that !!
An error appears when the player tries to do something in that gui.

#### Steps to reproduce the behavior:

1. /is challenges
2. right click on a random challenge
3. opens a Anvil Gui
4. place an item from your inventory in the anvil gui
5. change the name into e.g. `test`
6. take the item
7. error appears: `Given value "test"  is not integer`
8. hope you get your item back and close gui

#### Server / BentoBox information:

```
Running PAPER 1.13.2.
BentoBox version: 1.6.0-SNAPSHOT-b1298
commands.bentobox.version.database
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.5.2.1-SNAPSHOT-b127 (ENABLED)
BSkyBlock 1.6.0-SNAPSHOT (ENABLED)
Challenges 0.8.0-SNAPSHOT-#285 (ENABLED)
Level 1.6.0-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)
```
#### Screenshots / Server log

![Screenshot_20190731_210928](https://user-images.githubusercontent.com/28690790/62240713-d5ee1000-b3d7-11e9-8610-a45957a962ff.png)

#### Expected behavior / Additional context

A player should never ever be able to summon an AnvilGui
A player should not have to worry about which click (left/right) to use to complete the challenge.

**Comment by BONNe** [comment]
So, this is a way how I implemented multiple completions at once.

If a player write any number, then addon will try to complete a challenge multiple times.

f.e.
A challenge requires 64 stone, and a player has 5 stacks:
a) if player writes 3, then 3 he will complete challenge 3 times.
b) if player writes >5 then he will complete challenge 5 times only.
c) if a player writes anything that is not a number then he will get an error message.

**Comment by x1p** [comment]
Owkee, that was unexpected. :-)
I'll change my language file to explain better what can be expected there.

**Comment by x1p** [comment]
Oh btw: you can not fill in a number without placing an item in the anvil.
After the completion of the challenge, the inventory is all mixed up. Armor is disappeared, tools are in the workbench. Restores itself if the player relogs but it's very confusing.

**Comment by x1p** [comment]
After the completion of the challenge
![Screenshot_20190731_223859](https://user-images.githubusercontent.com/28690790/62246531-19e71200-b3e4-11e9-9c45-fed75afaca04.png)

Player relogs and it's back to normal
![Screenshot_20190731_223929](https://user-images.githubusercontent.com/28690790/62246578-3420f000-b3e4-11e9-9713-1f1033312c9a.png)

**Comment by x1p** [comment]
Can we have an option to decide to enable/disable right click functionality?

I foresee players complaining for missing items. I'm afraid for possible dupe issues. There too many clicks needed, too complicated for some players, too few advantages: cuz it's probably faster to click 5 times.

**Comment by BONNe** [comment]
I will add the ability to disable/enable this gui.
But it is weird, that you should place item, or that it even allows to place it there. I will investigate it.

**Comment by x1p** [comment]
The moment the anvilgui appears, the inventory is mixed up. Just a moment, I will place screenshots of every step

**Comment by BONNe** [comment]
Reintroduced MultipleCompeletion GUI in build 0.8.0-b334.
If you run into issues with GUI messing inventory, please create a new bug report.
