### ISSUE TITLE
Reward and required Items missed

### ISSUE THREAD

**Issue by Tomvapor** [BentoBoxWorld/Challenges#165]
### Description
When I create a inventory challenge with required items and rewards, i get this issue.

#### Steps to reproduce the behavior:

1. /bsb challenge
2. Create Challenge
3. /is challenge
4. I can see the challenge (see picture)

#### Server / BentoBox information:
newest version of bentobox and addons

#### Screenshots / Server log
https://ibb.co/hH793rG
no server errors

**Comment by BONNe** [comment]
Your Lang files are outdated.
It is necessary to update them.

Currently, there are 2 ways:
- Adding missing strings manually
- Removing challenges folder in lang directory and allow to regenerate them.

**Comment by Tomvapor** [comment]
Thank you very much.
