### ISSUE TITLE
Experience and money rewards incorrect or missing for 'Level Challenges'

### ISSUE THREAD

**Issue by Waterman1001** [BentoBoxWorld/Challenges#169]
### Description

When using the GUI to setup the challenges, I have set the experience reward for 'Novice Level' to 100, but it keeps showing 3.
Also, for the other levels it does not show the money or experience rewards.
I'm hoping this is a bug and it can be fixed.
Also say it if it is some problem of me haha.

#### Steps to reproduce the behavior:

1. Open challenge setup menu with /bsbadmin challenges
2. Go to Edit Level Challenges
3. Check the descriptions and see that they are incomplete.

#### Server / BentoBox information:

Running SPIGOT 1.14.4.
Database: JSON
Using: BentoBox version: 1.6.0-SNAPSHOT-b1317
Using: BSkyBlock 1.6.0-SNAPSHOT-b423 (ENABLED)
Using: Challenges 0.8.0-SNAPSHOT-#309

#### Screenshots / Server log

Here you can see that my experience rewards keeps showing '3', while i've set this to 100:
https://media.discordapp.net/attachments/393756208990912523/612746092530106388/unknown.png

Here you can see that the rewards are not shown although I did set them up :S:
https://media.discordapp.net/attachments/393756208990912523/612746296087805952/unknown.png
This holds for all the other level challenges/rewards.

Thank you so much in advance for your response and for your help and support!

**Comment by BONNe** [comment]
2 Different problems.
Both fixed in the latest snapshot.
