### ISSUE TITLE
NPE during InventoryClickEvent in Challenges window

### ISSUE THREAD

**Issue by runelynx** [BentoBoxWorld/Challenges#170]
**Description**
Clicking slot 0 in the challenges pop-up window is fine... but clicking slot 1 (both are populated with challenges) results in an NPE in console.

**Steps to reproduce the behavior:**

![image](https://user-images.githubusercontent.com/5877481/63238196-18965180-c1fa-11e9-8296-d11e03264ebc.png)

**Expected behavior**

**Screenshots**

**Server Information:**
 
![image](https://user-images.githubusercontent.com/5877481/63238215-2d72e500-c1fa-11e9-848e-fc9c250ddd5d.png)

**Additional context**

**Comment by BONNe** [comment]
There should be an error with one of your challenge.
Icon for one of your challenge is not a valid ItemStack. 

Not sure how and why it happened.
