### ISSUE TITLE
challenges.gui.item-description.item

### ISSUE THREAD

**Issue by FunnysBanana** [BentoBoxWorld/Challenges#171]
I updated to the new 0.8 version and saw this in /is challenges:

https://puu.sh/E7ZRp/18648a42a8.png

**Comment by BONNe** [comment]
Yea, you need to update your locales.
Each update may bring a new translation, and without an update, it will show up like this.

To update locale, you either need to regenerate challenges lang (by removing challenges folder in locales) or adding missing strings in your language file.
