### ISSUE TITLE
Farmer challenge not working after fixing typos

### ISSUE THREAD

**Issue by doitliketyler** [BentoBoxWorld/Challenges#18]
Its seems like the Farmer challenge isn't working even after updating the config with the right item names (carrot & potato). Its telling my players:

"You do not have enough Carrots to complete this challenge!"

Thoughts?

**Comment by BONNe** [comment]
I have investigated this issue and found, that there is an error how changing items for a challenge is implemented.

When adding items into MenuPanel it adds metadata for ItemStack element, that was not there before. [PanelItem.java:48](https://github.com/BentoBoxWorld/bentobox/blob/master/src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java)
Then this meta data is stored in ChallengesObject and it breaks ItemStack.isSimilar() method, as it compares also meta data.
So when a user tries to complete the challenge, ItemStack in his inventory is with meta = null, but required an item in Challange are with meta = {MetaData object}, so it does not allow to complete challenge anymore.

I do not know the proper fix for this issue, as if meta data is not changed in PanelItem object, then it will show them in GUIs, but if change how it checks for elements in inventory by ignoring meta (Inventory.constains(Material, Amount)) then it will disable enchanted items, potions and others in challenges.

**Comment by BONNe** [comment]
Implemented and fixed in latest snapshot.
