### ISSUE TITLE
Challenges icons show paper; allow completion without req'd items

### ISSUE THREAD

**Issue by runelynx** [BentoBoxWorld/Challenges#182]
### Description
Some of my challenges are not showing the proper icon as defined in YML. Also, they require items, lets say 64 Cactus... and the plugin lets the player complete it and gives the reward even though the player does not have the item.

#### Steps to reproduce the behavior:
Sample here...

![image](https://user-images.githubusercontent.com/5877481/64481975-0ece9100-d19d-11e9-90e2-368e1d0c188c.png)

From challenges.yml 

    cactusfarmer:
      friendlyname: 'Cactus Farmer'
      description: 'Collect 64 Cactus'
      icon: CACTUS
      level: 'Swabbie'
      type: inventory
      requiredItems: 'CACTUS:64'
      #requiredMoney: 10
      takeItems: true
      itemReward: 'SAND:10'
      rewardText: '10 Sand'
      #rewardcommands:
      #- kit tools [player]
      moneyReward: 10
      expReward: 30
      permissionReward: ''
      repeatable: true
      repeatItemReward: 'SAND:1'
      repeatRewardText: '1 sand'
      repeatMoneyReward: 1
      repeatExpReward: 10
      maxtimes: 100
      resetallowed: true

#### Server / BentoBox information:
![image](https://user-images.githubusercontent.com/5877481/64481984-260d7e80-d19d-11e9-9e3a-f747ae695f20.png)

**Comment by BONNe** [comment]
Yea, that is the reason why ASkyBlock challenge converter is removed in the latest snapshot.
YAML file converter never worked and it was too complicated to fix it.
