### ISSUE TITLE
how to add a command at the “command block” reward 

### ISSUE THREAD

**Issue by Jupiterbe** [BentoBoxWorld/Challenges#183]
### Description

In the chalenges at the “command block” reward
how can we add a command that will be excecuted.
we open the chat window but cant type a command with a /command in front and if we use "/command" it always says that its a wrong command?

![download](https://user-images.githubusercontent.com/43099691/64491776-7c95be00-d26c-11e9-81ad-147dd65bd79b.png)

how is the format to use commands?

#### Server / BentoBox information:

Bentobox 1.6

**Comment by BONNe** [comment]
Oh, it do not need '/'
Just a command.

**Comment by BONNe** [comment]
I tested and / is not necessary.

**Comment by Jupiterbe** [comment]
tested and it works like a charm :)
