### ISSUE TITLE
Challenges interface - add new challenge not working

### ISSUE THREAD

**Issue by runelynx** [BentoBoxWorld/Challenges#184]
#### Describe the bug
Clicking add new challenge icon in the GUI closed the GUI and put an error in chat. Subsequent attempts to click add new challenge simply do nothing.  

![image](https://user-images.githubusercontent.com/5877481/64493853-5b1bde80-d23a-11e9-9639-2e67d115cbf2.png)

![image](https://user-images.githubusercontent.com/5877481/64493856-63741980-d23a-11e9-96f3-53222939d204.png)

Note this error is in console from about 7 mins ago 
![image](https://user-images.githubusercontent.com/5877481/64493869-99190280-d23a-11e9-8672-6d832f47f1e2.png)

#### Server
Paper 1.14.4

![image](https://user-images.githubusercontent.com/5877481/64493875-aafaa580-d23a-11e9-8182-af53ca28c57b.png)

![image](https://user-images.githubusercontent.com/5877481/64493878-b4840d80-d23a-11e9-9522-035797da5090.png)

#### Plugins

```
_______
```

##### BentoBox and Addons
/bentobox version in-game does nothing. No error in console. I updated to the latest 1.7 build today. 

_______
```

##### Configuration
<!-- /!\ Leaving this section blank will result in your ticket being closed without further explanation. -->
<!-- Please replace the underscores with your answer. Do not remove the '*' characters. -->
 - Database: **________** <!-- Available options: YAML, JSON, MYSQL, MARIADB, MONGODB -->

### Additional context
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->

**Comment by runelynx** [comment]
Server restart got version command working
![image](https://user-images.githubusercontent.com/5877481/64493969-d4680100-d23b-11e9-8de0-4bc036db146a.png)

**Comment by runelynx** [comment]
Same behavior with challenges menu unfortunately.

![image](https://user-images.githubusercontent.com/5877481/64493974-e5187700-d23b-11e9-8071-92e21b5e8cc1.png)


No errors in console

![image](https://user-images.githubusercontent.com/5877481/64493980-f8c3dd80-d23b-11e9-9721-c8f2bd09c75d.png)

**Comment by BONNe** [comment]
Probably you need to update locale.
And then check if everything is working?

**Comment by runelynx** [comment]
Well my prior bug you closed yesterday said my 2500 lines of challenges config that was converted is useless.... so I wiped all challenges data and will start retyping it today.

**Comment by runelynx** [comment]
Ok clicking Add new Challenge now generates a chat box response. Is this intended? 

![image](https://user-images.githubusercontent.com/5877481/64494213-0890f100-d23f-11e9-8130-3eaf23f03df8.png)

**Comment by runelynx** [comment]
Does that mean a challenge name? It's kind of unclear.

**Comment by runelynx** [comment]
I put in "Challenge 1" and hit Enter; it gives me this GUI:

![image](https://user-images.githubusercontent.com/5877481/64494231-35450880-d23f-11e9-9ba8-2ce082068b84.png)

**Comment by runelynx** [comment]
Ok I havent gone through the whole thing yet but it appears to be working. Thanks for the quick reply.
