### ISSUE TITLE
An Internal Error Occured - Challenges

### ISSUE THREAD

**Issue by TheVigilantWolf** [BentoBoxWorld/Challenges#186]
#### Describe the bug

I am currently running CraftBukkit1.14.4, BentoBox, BSkyblock, Biomes, Levels are all working great, however I cannot get Challenges to work. Commands "/bsb challenges import defaults" or "/bsbadmin challenges" give me 'An internal error occurred while attempting to perform this command"
#### Steps to reproduce the behavior

1. Stop Server
2. Install BentoBox
3. Start Server
4. Stop Server
5. Insert Levels, Biomes, Challenges
6. Start Server, join server
7. Type commands mentioned above, and receive error messages
#### Screenshots and videos

[BentoBox & Addons Versions](https://cdn.discordapp.com/attachments/310623455462686720/621548672328532007/f5a849c2adc64219a2b444232cff60e4.png)
[bsbadmin challenges](https://cdn.discordapp.com/attachments/310623455462686720/621548997571772438/a976c633c158c96bf8373a2ff04c8ede.png)
/[challenges](https://cdn.discordapp.com/attachments/310623455462686720/621549380582899743/21853383c2945f72f618057f3f13fab8.png)
#### Expected behavior

I'm expecting to open the admin GUI and/or import default challenges that come with the addon
### Environment
CraftBukkit 1.14.4
#### Server

 - OS: **Windows**
 - Java version: **8 Update 221**

#### Plugins

```
dynmap, WorldEdit, Hordes, SpawnerSilk, RottenFlesh2Leather, VoxelSniper, ClearLag, PermissionsEx, Craftconomy3, WorldBorder, Vault, ActionHealth, EssentialsX, BentoBox, EssentialsChat, Multiverse-Core, GameModeInventories
```

##### BentoBox and Addons

```
Running BUKKIT 1.14.4
BentoBox version 1.7.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.01.1 (ENABLED)
BSkyBlock 1.6.0 (ENABLED
Challenges 0.8.0 (ENABLED)
Level 1.6.0 (ENABLED)
```

##### Configuration

 - Database: **JSON** 

### Additional context

CONSOLE OUTPUT:
https://pastebin.com/TbQxxUyD

**Comment by BONNe** [comment]
Solved.
The issue with outdated DynMap plugin.
