### ISSUE TITLE
Last challenge > Next Level

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#187]
#### Describe the bug

When the last challenge of a level is done, the Challenge GUI remains open and the new level does not appear immediately. You have to close the challenges gui, open it again, then the new level is loaded.
This will likely not be understood by players. They will think that they skipped a challenge and will stare to the gui like forever to look for the one they seem to miss.

#### Steps to reproduce the behavior

Do every challenge of 1 level.
Click the last one to complete the level
See that the gui will not change and go to the next level.
Then close the gui.
Open the /is challenges gui again
Note that the new level is loaded.

#### Expected behavior

The last challenge of a level should trigger the new level to load, or, if that's not possible, it would have to close the gui when the level is completed.

#### Server

 - OS: **Linux/Ubuntu**
 - Java version: **OpenJDK 1.8.0**

#### Plugins

```
BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, Vault, WorldBorder, WorldEdit, WorldGuard
```

##### BentoBox and Addons

```
Running PAPER 1.14.4.
BentoBox version: 1.8.0-SNAPSHOT-b1373
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.2-SNAPSHOT-b141 (ENABLED)
BSkyBlock 1.7.0-SNAPSHOT-b451 (ENABLED)
Challenges 0.8.0 (ENABLED)
Level 1.7.0-SNAPSHOT-b284 (ENABLED)
Limits 1.7.0-SNAPSHOT-b165 (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
Warps 1.6.2-SNAPSHOT-b180 (ENABLED)
```

##### Configuration

 - Database: **JSON**

**Comment by BONNe** [comment]
Yes, it is known bug.
Unfortunately, no ETA on fixing.
