### ISSUE TITLE
Challenges description missing from menu

### ISSUE THREAD

**Issue by datatags** [BentoBoxWorld/Challenges#189]
#### Describe the bug

For some reason, when I open the challenges menu it doesn't show challenge descriptions (description text, required items, rewards, etc.)  It occurred after updating to BentoBox 1.7.0 and BSkyBlock 1.6.0 and Challenges 0.8.0
#### Steps to reproduce the behavior

Steps I took:

1. Update BentoBox to 1.7.0 from 1.5.3.  I notice Challenges (0.7.5?) aren't working, so I update BSkyBlock(from 1.5.0 to 1.6.0) and Challenges (0.7.5 to 0.8.0).
2. Remove Challenges databases and config directories as I am wanting to use the BSkyBlock default challenges rather than the previously imported ASkyBlock challenges
3. Purge challenges through /bsb challenges
4. Import challenges via /bsb challenges (all imports said successful in chat)
5. Open challenges GUI, notice all descriptions are missing.

#### Screenshots and videos

![2019-09-23_14 02 05](https://user-images.githubusercontent.com/17661376/65462538-dc629c00-de0a-11e9-8056-b07f208759ec.png)
![2019-09-23_14 01 42](https://user-images.githubusercontent.com/17661376/65462545-dff62300-de0a-11e9-84b4-918698638667.png)
![2019-09-23_14 01 52](https://user-images.githubusercontent.com/17661376/65462556-e6849a80-de0a-11e9-9033-bc32db5f17bc.png)
#### Expected behavior

The challenges to have description and such as they did previously before updating.
### Environment
System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17) Host:  Linux 4.9.0-9-amd64 (amd64)
#### Server

 - OS: **Debian Stretch**
 - Java version: **java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)**

#### Plugins

```
AntiEnderChest, BentoBox, BlocksHub, Chat*, ChatControl*, Citizens, CoreProtect, CrazyEnchantments, DiscordSRV, EditableSign, EndCrystalLootBoxes, Essentials, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EventDebug*, GriefPrevention, LuckPerms, mcMMO, Multiverse-Core, MysqlEcoBridge*, OpenInv*, PhantomSpawnControl, ProtocolLib*, QuickShop, SendMessage*, Vault, VillagerData, WorldEdit, WorldGuard
```

#### BentoBox setup
??
##### BentoBox and Addons

```
[13:54:49 INFO]: Running PAPER 1.14.4.
[13:54:49 INFO]: BentoBox version: 1.7.0
[13:54:49 INFO]: commands.bentobox.version.database
[13:54:49 INFO]: Loaded Game Worlds:
[13:54:49 INFO]: bskyblock (BSkyBlock): Overworld, Nether, End
[13:54:49 INFO]: Loaded Addons:
[13:54:49 INFO]: BentoBox-InvSwitcher 0.0.4 (ENABLED)
[13:54:49 INFO]: Biomes 1.6.0.1 (ENABLED)
[13:54:49 INFO]: BSkyBlock 1.6.0 (ENABLED)
[13:54:49 INFO]: Challenges 0.8.0 (ENABLED)
[13:54:49 INFO]: DimensionalTrees 2.0.0-SNAPSHOT (ENABLED)
[13:54:49 INFO]: Level 1.6.0 (ENABLED)
```

##### Configuration

 - Database: **JSON** 
Full config: https://pastebin.com/DZS6DacC
Challenges config is default due to removing directory.

**Comment by BONNe** [comment]
Realy? Does nobody read release notes?
https://github.com/BentoBoxWorld/Challenges/releases/tag/0.8.0

## UPGRADE WARNING
In version 0.8.0 addon change data storage, and on server start-up, it will show, that challenges are not implemented. It is necessary to migrate data to a new format, and it can be done with command /[gamemode_admin] challenges migrate, or by clicking on migrating button in admin GUI.

As always, update your locales folder.
**Be aware, Challenges Lore and Level Lore structure are changed. If you upgrade, it can show empty description for both of them. To enable, you either need to delete existing config.yml and regenerate it, copy challenge-lore and level-lore settings from source code or add necessary lore values via ingame Admin GUI, by clicking on Settings and then on the challenge and level lore buttons.**

**Comment by datatags** [comment]
I did regenerate the config, (as part of deleting the config directory) but I must have done it incorrectly or in the wrong step.  I tried again and it works now.  Thank you!
