### ISSUE TITLE
Choose from all Materials for challenge icon

### ISSUE THREAD

**Issue by runelynx** [BentoBoxWorld/Challenges#190]
#### Is your feature request related to a problem?

No problem. I'd like to be able to choose from the full set of Material icons when setting the icon for a challenge. Right now the list is lengthy, but incomplete. I cannot choose cookie, for example.

#### Describe the solution you'd like us to implement.

Add all materials.

#### Describe alternatives you've considered.

.... :)

**Comment by BONNe** [comment]
It should contain all the items. 
I use all items available in Spigot, just dropping items, that cannot be drawn in GUI, like carrots (plant), potatoes, piston heads, water and etc.
