### ISSUE TITLE
Challenges icon configuration

### ISSUE THREAD

**Issue by alexandre14062** [BentoBoxWorld/Challenges#191]
Good evening, I would like to make a suggestion about the configuration of the icon of challenges, I think it would be much more convenient to need to simply slide the item over the area of the icon to change it rather than go into the config and write manually the icon.

**Comment by BONNe** [comment]
About which icon you are talking? As i am pretty sure that all icons changes can be done via ingame GUI by selecting icon from a menu.

**Comment by alexandre14062** [comment]
An answer? Well as I said above, it's the **icon of challenges**

**Comment by BONNe** [comment]
I cannot find any issues with changing challenges icon via GUI.
Level and challenges icons are easy to change without any problems.

https://youtu.be/8AH4SHWyfQQ

**Comment by alexandre14062** [comment]
that's a problem https://youtu.be/wf0OiNEmbwc

**Comment by BONNe** [comment]
Please provide output of `/bentobox version` command.

**Comment by BONNe** [comment]
The issue why it is not working for you is because you are using a 1.14.4 version of challenges for 1.13.2 server. 
There is releases 0.8.0-1.6.0 version that works on 1.13.2 servers. Newest versions do not support 1.13.2.
