### ISSUE TITLE
Required-items traductable

### ISSUE THREAD

**Issue by PapiCapi** [BentoBoxWorld/Challenges#194]
#### Is your feature request related to a problem?

Make required-items traductable.

#### Describe the solution you'd like us to implement.

For me, the easier way to do it, is, as the rewards, add a required-text where admins will put what they want to display.

**Comment by BONNe** [comment]
Sorry, I do not understand what do you mean with your text.

If you ment to hide:
```
required items:
- ITEM 
- ITEM
- ITEM
```

then you can do it by adjusting Challenge Lore Message in Settings via Admin GUI.

**Comment by PapiCapi** [comment]
In fact, i want my players to see what they need to complete the challenge but some of them don't understand the name of english items.
In fact, in my server, i set the reward text to the french version of english items given. (http://prntscr.com/phhc2w) so i was asking if it was possible to do the same thing with required-items

**Comment by BONNe** [comment]
Oh, you want them translatable?
Yes, I am planning to implement this.
#133
