### ISSUE TITLE
Edit challenges in GUI

### ISSUE THREAD

**Issue by tnht** [BentoBoxWorld/Challenges#195]
Hi,

Today i want change description of many challenges but when i click in BSBADMIN CHALLENGES gui on anvil with text "Edit challenges" nothing happend.

Check screen from console:
https://imgur.com/a/ASyIZCV

Other options like Edit level working good.

**Comment by BONNe** [comment]
This mean, you are using old, outdated Challenges Version.
Anvil GUI is removed, and message that material SIGN is missing, means you are using 1.13.2 version on 1.14.4 server.

And I cannot tell you anything more, as you do not provide the necessary information.

**Comment by tnht** [comment]
Could you send me actually version Challenges?

pt., 11 paź 2019 o 15:32 BONNe <notifications@github.com> napisał(a):

**Comment by BONNe** [comment]
In the release tab, you can get latest official release version.

**Comment by tnht** [comment]
I'm using Challenges-0.8.0-1.6.0.

Now i'm update to Challenges-0.8.0.
Perfect :)

Thank you!
