### ISSUE TITLE
Challenges Improvement Ideas

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Challenges#20]
_From @tastybento on July 15, 2017 21:44_

_From @tastybento on March 29, 2017 18:19_

_From @Poslovitch on March 22, 2017 10:45_

**CHECKLIST**

*Challenges*
- [ ] Requirements: permissions or challenges (or completed X-times challenges) to be able to complete (and show, so add a config option to hide challenges if their permission/challenges requirements are not completed) a challenge.
- [ ] Requirements: island levels (for PLAYER & ISLAND)
- [ ] Requirements: support for just one element from a list of items/blocks/entities (e.g: "homestead": oak door or birch door or spruce door...)
- [ ] Requirements & Rewards: Support for potion arrows, spawn eggs, enchanted books, custom named &/or enchanted items, fireworks
- [ ] Rewards: default & special repetitions rewards (e.g: default reward is stone, 5th repetition reward is dirt)
- [ ] Add: "CUSTOM" challenge type, which can only be completed by admin command or by API.
- [ ] Completion: Challenges can be completed again after an specified amount of time

*Tweaks*
- [ ] "INVENTORY" challenges will be called "PLAYER"
- [ ] List missing requirements when wanting to complete a challenge
- [ ] Add config option to make possible to complete PLAYER challenges in all worlds.
- [ ] Handle the case there are no challenge levels
- [ ] Add customisable check range for ISLAND challenges
- [ ] Require money, perms or other to unlock next level
- [ ] Add option to disable challenges (usechallenges)

*GUI*
- [ ] Convert to the new type of Panels ("Panels rewrite"): pages, no more cursor position reset, customisable...
- [ ] Display how many times the challenge has been completed (except if not repeatable)
- [ ] Challenge levels can now have their own display name & item.

*API*
- [ ] Remake challenge-related API

*Bazar*
- [ ] Challenge turn-in multiple times in one command / Click/command to complete as much as possible of the/all challenge
- [ ] #93 - "if a challenge were to be completed, the team member who completed it received the rewards while it would still be counted as completed for the other members."
- [ ] Seasonal challenge categories
- [ ] CompletedChallenges count and IncompletedChallenges count placeholders
- [ ] Progress bar https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/210
- [ ] Chance to receive a reward
- [ ] Give the placeholder %challenge_#_completed% which would allow to have, eg ![](https://puu.sh/xciCJ/d4102dac26.png) when uncompleted, ![](https://puu.sh/xde5v/dbc192e90c.png) to display how much time it has been completed...

_Copied from original issue: tastybento/askyblock#566_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#10_

_Copied from original issue: BentoBoxWorld/bentobox#12_

**Comment by BONNe** [comment]
Hello, 
This TODO list is not updated, or this ADDON must be rewritted from scratch by using this TODO list?

**Comment by Poslovitch** [comment]
These were ideas to improve ASB's challenges

**Comment by TheWranger** [comment]
Would the panel rewrite also allow for changing the item used for showing the next obtainable level? Would be a nice thing to be able to customize

**Comment by Poslovitch** [comment]
That theorically would ;)

**Comment by BONNe** [comment]
I will split into feature requests that are not implemented yet and close this one.
