### ISSUE TITLE
Problem with challenges

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#201]
I converted some challenges from askyblock and going to look at the challenges within the game I noticed that the "requiredItems" "rewardcommands" "itemReward" sections are also viewed

These sections should not be seen, also because in this way it would not make sense to put written descriptions. Is it possible to solve this problem and hide / hide the written ones? Thanks.

https://imgur.com/cfFuVzv

**Comment by BONNe** [comment]
You can modify your lore message settings via in-game admin GUI
`/[gamemode_admin] challenges` under settings menu. There you can edit challenge lore and level lore as you want.

**Comment by Manu5656** [comment]
From that section you can't solve what I asked for ... maybe you didn't understand what I was referring to.

The sections with the ids of the requested items, the ids of the prize items and the commands that are made must NOT be visible ..

How can this problem be solved?

**Comment by Manu5656** [comment]
These things (requested items, prize items, reward commands) should not be seen!
https://imgur.com/8hqf5Vf

**Comment by BONNe** [comment]
Yes, you can. That section is made exactly for that. To remove elements from LORE that you do not want to see.

**Comment by Manu5656** [comment]
Can you tell me exactly what I should select?
The video is private :/

**Comment by Manu5656** [comment]
https://imgur.com/Amv2c7B
I see in this guide only options to do reset, remove challenge, levels and similar things ..

**Comment by BONNe** [comment]
Sorry, now it is public. Forgot to publish.

**Comment by Manu5656** [comment]
it's still private lol

**Comment by Manu5656** [comment]
I saw the video now.
To me on "description of the challenge" there is written as description "Current value: LSTDE" and if I click on it the menu of an anvil opens with the written one .. why? What should I do?

**Comment by BONNe** [comment]
Oh, you are using an older version.
Read the description in challenge addon config. All letters are described there.

**Comment by Manu5656** [comment]
Ok thank you
