### ISSUE TITLE
Disable monetary reward being displayed for challenges when no economy plugin is found.

### ISSUE THREAD

**Issue by ghost** [BentoBoxWorld/Challenges#203]
### Description
When browsing challenges in-game, if there is a monetary reward for a challenge it is displayed in the challenge info panel.  If no economy plugin is installed, monetary rewards are disabled.  This functionality is confusing for the player, they see money as a reward and do not get it.  
#### Is your feature request related to a problem?

Not really.

#### Describe the solution you'd like us to implement.

I would like BentoBox to hide the money reward from the Challenge Info Panel when the money rewards are disabled.

#### Describe alternatives you've considered.

None.

**Comment by BONNe** [comment]
A fast hack can be done by setting empty translation for money rewards.
But it makes a lot of sense, to do not display information that is not relevant. 
Will implement in the next release. (no eta)

**Comment by Reg-Ed** [comment]
Super-duper, thank you.

**Comment by BONNe** [comment]
Implemented in 1.0 version.
