### ISSUE TITLE
More additions for improve the addons 

### ISSUE THREAD

**Issue by AFGAME** [BentoBoxWorld/Challenges#204]
Hello, i would have thought to add an option for say when a challenge is completed or not (example in my screenshot) and to propose yml for edit challenge because it's very hard for a begginer of the plugin. 
Sorry for my english but i speak french :) 

Thanks you for listen, hopping that this will be put in place.
https://user-images.githubusercontent.com/50768722/69808901-e9c04c00-11e8-11ea-98ac-bef22480cbd1.png

**Comment by BONNe** [comment]
First of all... there is no screenshot.
Secondly... no YAML editing will be not provided at all. -> detailed explanation (https://github.com/BentoBoxWorld/Challenges/issues/202#issuecomment-554741280)

All editing can be done via the admin GUI. Texts can be edited in translations. So it is hard to say what else should be provided.

**Comment by AFGAME** [comment]
Sorry The screen is really buggy but I just added it

**Comment by BONNe** [comment]
Ok, currently it is possible to add a message only if the challenge is completed. If it is not, message does not show up. 
Hmm... I need to think about a way how to implement it, as not all want to show it.

**Comment by BONNe** [comment]
I will decline this one because I do not know how to do it nicely. 

Challenges have 2 types of repeatable challenges:
to a fixed number 
infinite

Because "repeatable" shows only true/false, it is not full information about the challenge.
