### ISSUE TITLE
Auto-complete challenges

### ISSUE THREAD

**Issue by chrs944** [BentoBoxWorld/Challenges#206]
Hi great plugin.

Have you given any thought to adding an auto complete for challenges? It could be a setting in the admin that you could turn on or off.

For example, instead of a player typing /island challenges and then clicking on the challenge to complete it, would it be possible for the plugin to detect if the challenge has been completed?

Now as I'm typing this I can see it getting a little more complex because of challenges that take away items, such as trading logs for clay. I suppose you could have a check box for marking the challenge as able to be auto completed.

Example, an auto complete challenge could be that the player collected 50 cobblestone. While an example of a non-auto complete challenge would be trading 50 cobblestone for a sapling since the player may not want to complete this challenge.

**Comment by BONNe** [comment]
Such automation would require constantly check every player inventory and surrounding for blocks/entities.

If it was just inventory checks, it could be doable with some performance impact, however, with blocks/entities checks... it will just be too resource intensive.
