### ISSUE TITLE
Broken Buttons

### ISSUE THREAD

**Issue by skullblaze56** [BentoBoxWorld/Challenges#213]
#### Describe the bug

Need help with challenges addon
I'm on the latest BSkyblock and Bentbox and the following buttons in /bsbadmin challenges do not work: Edit Challenge (Anvil), Remove Challenge (Lava Bucket), Edit Settings (Crafting Table), Add New Level (Book), Add Challenge (Water Bucket inside the levels section), and lastly when trying to complete challenges for players nothing happens when i click on them. Also, am I supposed to have a config file where I can edit the challenges there? It's much easier for me that way and I've never got one when installing the challenges.

#### Steps to reproduce the behavior

Click the exact buttons I outlined in my screenshots, for me, nothing happens afterwards.
#### Expected behavior

I believe that the buttons should do the functions they were made for, although I could just be using the program wrong.
#### Screenshots and videos (Optional)

[https://prnt.sc/qsk99r](url)
[https://prnt.sc/qsk9d0](url)
[https://prnt.sc/qskc5v](url)
##### BentoBox Version (Mandatory)

```
BentoBox version: 1.10.0-1.13.2 / Challenges 0.8.0-1.6.0 (ENABLED)
```

#### Plugins (Optional)

```
AmazingFishing, AutoMessage*, BentoBox, Citizens, CommandNPC*, DeluxeChat, Essentials, EssentialsSpawn, FastAsyncWorldEdit, Holograms*, LiteBans, LuckPerms, mcMMO, Multiverse-Core, PlaceholderAPI, PlotSquared, PlugMan, Quests*, QuickBoard*, SimplePets, TheAPI, Vault, WorldEdit, WorldGuard
```

**Comment by BONNe** [comment]
For me, it looks like challenges upgrading to 0.8 version was not sucessfull. Did you run /[gamemode-admin] challenges migrate when you upgrade to 0.8 version?

About single file...
Theoretically it is possible to get single file, but i doo not suggest it to use, as file format is not tolerant for any mistake.

You can get the file with challenges defaults export command.
However, to import challenges back, you will need to remove existing from server... (tnt button) and then import with challenges defaults import command.

**Comment by skullblaze56** [comment]
I did run the command, it says every file is valid but will not work. As for the file, it works now, thank you

**Comment by skullblaze56** [comment]
My console only shows this as well. [https://image.prntscr.com/image/PyAr-zGgSBKS9R7hOw2GfA.png](url)

**Comment by BONNe** [comment]
So, could you please upload (or share) output of that single file?
