### ISSUE TITLE
requirements' and rewards' item name can't be translated

### ISSUE THREAD

**Issue by inuEbisu** [BentoBoxWorld/Challenges#215]
https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/java/world/bentobox/challenges/panel/CommonGUI.java
`itemStack.getType().name()`
Could you please change the code? Thank you very much.

**Comment by BONNe** [comment]
@Poslovitch and @tastybento 
As this is not only Challenges addon problem but may affect any addon that uses materials and item stacks, I think this should be feature into BentoBox core.

Currently, I can think of 2 ways how this can be solved:

1. Provide a translation for every block in some repository.
2. Use NMS to acquire the correct item name as it is done here: [LocaleLib](https://github.com/PikaMug/LocaleLib)

**Comment by BONNe** [comment]
This is done with #276
Requires review.
