### ISSUE TITLE
"Island type" challenges don't detect entities in nether or end islands

### ISSUE THREAD

**Issue by Blatower21** [BentoBoxWorld/Challenges#218]
**Description:**
When you have a challenge about being near to certain entities in nether or end the addon don't detect them.

**Steps to reproduce the behavior:**
-Create an island type challenge
-Select blaze or any mob
-Go to nether or end and spawn it
-Try to complete the challenge

**Expected behavior:**
Be able to complete this type of challenges in nether or end islands.

**Image showing for example a shulker not being detected:**
![2020-03-08_21 11 29](https://user-images.githubusercontent.com/31895420/76173810-6b792b80-6181-11ea-8e92-7c060b181b40.png)

**Environment**
`[00:16:09] [Server thread/INFO]: Corriendo PAPER 1.15.2.`
`[00:16:09] [Server thread/INFO]: BentoBox version: 1.11.1`
`[00:16:09] [Server thread/INFO]: Base de datos: JSON`
`[00:16:09] [Server thread/INFO]: Mundos de juego cargados:`
`[00:16:09] [Server thread/INFO]: bskyblock_world (BSkyBlock): Mundo, [nether_color]Nether, [end_color]End`
`[00:16:09] [Server thread/INFO]: Addons cargados:`
`[00:16:09] [Server thread/INFO]: Biomes 1.6.0.1-SNAPSHOT-b151 (ENABLED)`
`[00:16:09] [Server thread/INFO]: BSkyBlock 1.11.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Challenges 0.8.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Chat 1.0.1 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ControlPanel 1.7.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ExtraMobs 1.11.0.2 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Level 1.9.3 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Limits 1.9.2 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Warps 1.9.0 (ENABLED)`

**Comment by tastybento** [comment]
Yes, it does not seem to work in the nether or end even if the environment flags are set.

**Comment by NoHoPeLess** [comment]
The bug is still there https://ci.codemc.io/job/BentoBoxWorld/job/Challenges/400/

https://www.youtube.com/watch?v=4BOrKzkRaak

**Comment by BONNe** [comment]
@tastybento 
I could not reproduce it...
But if the error message is correct (not-on-island) then there is a check if the user is on his island:
https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/java/world/bentobox/challenges/tasks/TryToComplete.java#L540
The weird part is that it can fail only if BentoBox returns that player is not on his nether island.
But in the support channel, NoHoPeLess showed /is info images and both show the correct information.
Is it possible that locationIsOnIsland somehow fails without a reason in the nether?

**Comment by Blatower21** [comment]
For me it's fixed now with b400!
