### ISSUE TITLE
Challenge by island

### ISSUE THREAD

**Issue by Darkphenixs01** [BentoBoxWorld/Challenges#220]
#### Describe the solution you'd like us to implement.

I propose to make a choice in the configuration (player or island) or another challenge plugin so that the challenges are linked to the island and not to the player. (all players of the same island have the same / challenge with its advancement, if a player has completed a challenge it is completed for all players of the same island)

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Challenges/blob/6368585a57c1c7ae003620f1cf2e17846cd496de/src/main/resources/config.yml#L124
