### ISSUE TITLE
Database file cannot be converted to UTF-8 encoding

### ISSUE THREAD

**Issue by liaoxu2003** [BentoBoxWorld/Challenges#223]
The language of my menu is Chinese, but the data generated by the plugin is not UTF-8, which causes my language to appear garbled. How should I solve this problem?Thanks.

**Comment by tastybento** [comment]
@BONNe Any ideas?

**Comment by minhthanh920** [comment]
the same issue :(

**Comment by tastybento** [comment]
Hmm. I cannot replicate this problem yet.

I tried both manually and using the GUI. To set up I did:

1. Start server
2. Do `/bsb challenges`
3. Import the default challenges.

Then...

**Manually Edit**
1. Stop server
2. Edit the JSON file ( used VSCode, UTF-8 editor):
<img width="361" alt="Screen Shot 2020-04-12 at 3 44 04 PM" src="https://user-images.githubusercontent.com/4407265/79081672-72411400-7cd4-11ea-9936-64f0dd7c7224.png">
3. Restart the server
4. Do `/is challenges`:
<img width="570" alt="Screen Shot 2020-04-12 at 3 35 52 PM" src="https://user-images.githubusercontent.com/4407265/79081570-8a646380-7cd3-11ea-8c88-9cc67384b420.png">

This worked fine. I tried using the in-game GUI:

1. Do `/bsb challenges`
2. Use the GUI to edit the title, description and reward text:
<img width="400" alt="Screen Shot 2020-04-12 at 3 42 47 PM" src="https://user-images.githubusercontent.com/4407265/79081735-eed3f280-7cd4-11ea-835e-2486a931c6fc.png">

This works too.

Can you share what you do and where it fails, step by step?

**Comment by minhthanh920** [comment]
i did step by step, but it still cannot convert to UTF-8 encoding. i don't know what happened

**Comment by tastybento** [comment]
Hmm. 

What is your server OS?

What is your client OS?
