### ISSUE TITLE
Placeholder: Challenges Completed

### ISSUE THREAD

**Issue by CSmither** [BentoBoxWorld/Challenges#224]
**Description**

We would like a placeholder that shows the number of challenges completed, and another that shows the number of unique challenges completed.
The challenges completed placeholder will be a count of all challenges and will count multiple completions of the same challenge. The unique challenges will only count once for each challenge even if it is completed multiple times.
Not sure if this is implemented, though I can't find it anywhere in the docs or code, and it was requested in #74 but closed without resolution.

**Placeholder**: `%[gamemode]_challenges%` and `%[gamemode]_challenges_unique%`

**Comment by CSmither** [comment]
There appears to be a typo 
https://github.com/Cleymax/Challenges/commit/34848af8d342c008efbf47b91a78d0f4afc46061#diff-df0f31f23d0a3492308fbdd7ceb74dedR185
```
 + "_chalenge_lock_count",
```

**Comment by BONNe** [comment]
That code part is not used. It is incorrect.

**Comment by CSmither** [comment]
Oh ok apologies. Thank you.

**Comment by BONNe** [comment]
There is nothing to apologize :)

I am glad that someone at least tried to add it. As without it, I wouldn't bother to do it :D
