### ISSUE TITLE
Repaired items

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/Challenges#227]
Hey, I found little error in this addon:
It is not accepting repaired items (eg. golden helmet created by combining damaged helmets from mobtrap). 

Hope it is not too big deal to fix this. 

Regards, Kesims

**Comment by tastybento** [comment]
Are you able to confirm via the client that the helmets are 100% not damaged?

**Comment by BONNe** [comment]
So currently Challenges are ignoring "metadata" (data that contains extra information) only for rockets, enchanted and written books and filled maps.

Any other extra NBT tag to all other items will mark them as not equal.
