### ISSUE TITLE
Challenges that requires tools or armors don't work properly

### ISSUE THREAD

**Issue by Blatower21** [BentoBoxWorld/Challenges#229]
**Description:**
Some challenges don't detect armors and tools. Only you can complete them if you take them of the creative to complete it or you put in the require items the same armor and tools that you crafted duplicating them but then other players can't complete them.

**Steps to reproduce the behavior:**
- Create a challenge thar requires some parts of armor or tools
- Craft the items and try to complete the challenge with other account
- Try to complete the challenge and see that it says that you dont have the required items

**Expected behavior:**
Be able to complete this type of challenges that requires armors or tools again. And if possible even with enchanted ones.

**Environment**
`[00:16:09] [Server thread/INFO]: Corriendo PAPER 1.15.2.`
`[00:16:09] [Server thread/INFO]: BentoBox version: 1.13.0-SNAPSHOT-b1736`
`[00:16:09] [Server thread/INFO]: Base de datos: MARIADB`
`[00:16:09] [Server thread/INFO]: Mundos de juego cargados:`
`[00:16:09] [Server thread/INFO]: bskyblock_world (BSkyBlock): Mundo, Nether, End`
`[00:16:09] [Server thread/INFO]: Addons cargados:`
`[00:16:09] [Server thread/INFO]: Biomes 1.12.0-SNAPSHOT-b159 (ENABLED)`
`[00:16:09] [Server thread/INFO]: BSkyBlock 1.13.0-SNAPSHOT-b614 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Challenges 0.8.1 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Chat 1.0.1 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ControlPanel 1.7.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ExtraMobs 1.11.0.2 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Level 2.0.0-SNAPSHOT-b353 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Limits 1.12.0-SNAPSHOT-b211 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Warps 1.9.0 (ENABLED)`

**Other comments**
This type of challenges were working before de 0.8.1 Challenge's release. But **challenges thar requires enchanted items have same problem even before this update** (I mention this other problem here because of the similarity)

**Comment by BONNe** [comment]
Please, could you write:
`/bsb challenges defaults exprort`
And upload defaults.json file from `/plugins/bentobox/addons/challenges/` folder here?

**Comment by Blatower21** [comment]
I've just seen #227 and I believe is the same problem. Sorry for duplicate issue but enchanted items because of your response there it's same issue of  "Any other extra NBT tag to all other items will mark them as not equal."

**Comment by BONNe** [comment]
Could you still upload file?

**Comment by Blatower21** [comment]
That command doesn't exits

**Comment by BONNe** [comment]
Sorry, typo:
`/bsb challenges defaults export`

**Comment by Blatower21** [comment]
Yes, I know,  `/bsb challenges defaults export` doesn't exists. Only with "import" works.

**Comment by BONNe** [comment]
Crap :D 
I messed it again. I will need to review and fix naming for these commands.
It is `generate` at the end :D
