### ISSUE TITLE
[challengesToDo] and waiveramount not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/Challenges#23]
Please dont beat me for hudge amount of requests XD

to-complete: "Complete [challengesToDo] more [thisLevel] challenges to unlock this level!"
It always says 6 - its not changing

Also "waiveramount" seems to be not working. I always have to complete this 6 chalenges to go to next level, despite of configuration.

Now im not sure if any of other probles are reproductable, but you can look into it

**Comment by BONNe** [comment]
Implemented and fixed in latest snapshot.
