### ISSUE TITLE
Unable to hide lore

### ISSUE THREAD

**Issue by ShadowDragon7015** [BentoBoxWorld/Challenges#233]
#### Describe the bug

Unable to hide "REWARD_COMMANDS" from players viewing the challenge
#### Steps to reproduce the behavior

I go into "edit lore" and click the command block that says "REWARD_COMMANDS" and nothing happens, it just flashes the gui item
#### Expected behavior

challenges no longer showing what command is run when the challenge is completed
##### BentoBox Version (Mandatory)

```
>....=>.... [00:37:19 INFO]: Running PAPER 1.15.2.
>.... [00:37:19 INFO]: BentoBox version: 1.13.1
>.... [00:37:19 INFO]: Database: JSON
>.... [00:37:19 INFO]: Loaded Game Worlds:
>.... [00:37:19 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
>.... [00:37:19 INFO]: Loaded Addons:
>.... [00:37:19 INFO]: Biomes 1.7.0 (ENABLED)
>.... [00:37:19 INFO]: Border 1.0.7 (ENABLED)
>.... [00:37:19 INFO]: BSkyBlock 1.12.0 (ENABLED)
>.... [00:37:19 INFO]: Challenges 0.8.2 (ENABLED)
>.... [00:37:19 INFO]: Chat 1.0.5 (ENABLED)
>.... [00:37:19 INFO]: ControlPanel 1.7.0 (ENABLED)
>.... [00:37:19 INFO]: Level 1.9.3 (ENABLED)
>.... [00:37:19 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

 (i don't want players seeing the permission plugin running commands)

**Comment by BONNe** [comment]
Yea... probably I need to show some GUIs or explain more.

You need to click on RED glass pane on top of the GUI. And after that, you click on the item you want to remove.
