### ISSUE TITLE
some changes for the challenges

### ISSUE THREAD

**Issue by Orakha** [BentoBoxWorld/Challenges#234]
to make sure that the challenges can be completed in several stages, in case a challenge is hard enough to do, we can do it in stages.
For example for a quest of 36stack of cobble which would win 72 $ at the end, we can deposit stack by stack and we get 2 $ for each of them , so we don't have to complete it all at once

**Comment by BONNe** [comment]
It would be similar to the #144.

I would prefer to implement that, instead of this, as storing partially done challenges would be a nightmare.
