### ISSUE TITLE
Expert/Village challenge cannot be met by default

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/Challenges#238]
#### Describe the bug

One of the Expert challenges is a village with ten villagers. But villagers cannot be spawned naturally, so a default challenge cannot possibly be met. Some challenge reward should include villager_spawn_egg (minimum 2), so they can be bred to meet the challenge.

##### BentoBox Version (Mandatory)

```
>bbox version
[02:03:38] [Server thread/INFO]: Running SPIGOT 1.15.2.
[02:03:38] [Server thread/INFO]: BentoBox version: 1.14.0-SNAPSHOT-b1797
[02:03:38] [Server thread/INFO]: Database: JSON
[02:03:38] [Server thread/INFO]: Loaded Game Worlds:
[02:03:38] [Server thread/INFO]: world_skyblock (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
[02:03:38] [Server thread/INFO]: Loaded Addons:
[02:03:38] [Server thread/INFO]: Biomes 1.12.0-SNAPSHOT-b160 (ENABLED)
[02:03:38] [Server thread/INFO]: BSkyBlock 1.13.0-SNAPSHOT-b601 (ENABLED)
[02:03:38] [Server thread/INFO]: Challenges 0.9.0-SNAPSHOT-b416 (ENABLED)
[02:03:38] [Server thread/INFO]: ExtraMobs 1.11.0.2-SNAPSHOT-b4 (ENABLED)
[02:03:38] [Server thread/INFO]: Level 2.0.0-SNAPSHOT-b354 (ENABLED)
```

**Comment by BONNe** [comment]
Well... no.
Everyone can get villagers without any problems. No spawn eggs or spawners required.

If you do not know how I suggest visiting Minecraft Wiki.

Default challenges will not be adjusted for this. However, you can always create your own challenges where you add spawn egg if you think that acquiring a villager is something impossible.

**Comment by SlimeDog** [comment]
I am confused. Poslovich says it is not possible; you say it is.

Among other MC wiki pages, I have read
- [Village](https://minecraft.gamepedia.com/Village)
- [Village/Structure](https://minecraft.gamepedia.com/Village/Structure)
- [Village/Mechanics](https://minecraft.gamepedia.com/Village/Mechanics)
- [Villager](https://minecraft.gamepedia.com/Villager)
- [Zombie_Villager](https://minecraft.gamepedia.com/Zombie_Villager)

And as you can see from the [discussion](https://www.spigotmc.org/threads/bentobox-bskyblock-acidisland-skygrid-caveblock-aoneblock.406972/page-7#post-382514), I have tried to do.

I apologize if I have missed something obvious, but the only possibility I see is a zombie_villager, which can then be cured. I have not succeeded in spawning one (that I have seen). And the cure -- a golden_apple  and a potion of weakness -- would require killing 72+ zombie pigmen (minimum -- they do not always drop gold nuggets), and considerable investment in the nether. Is that what you are thinking?

Please advise. If you do not want to share the secret publicly, please PM on Spigot MC.

**Comment by BONNe** [comment]
Well, you already wrote that.
It is not a secret. Classic SkyBlock thing... catch 2 zombie villagers and cure them.

Yes, it requires a lot of investment, however, I easily can do it in a 1-2h play session. It is not hard.

**Comment by SlimeDog** [comment]
Thank you.
