### ISSUE TITLE
InventoryClickEvent error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Challenges#245]
#### Describe the bug
When click to player on complete challanges on /bsb challenges menu giving this error.

![image](https://user-images.githubusercontent.com/47111280/86563742-99268380-bf6d-11ea-8d38-0a59b69270e6.png)
![image](https://user-images.githubusercontent.com/47111280/86563775-a9d6f980-bf6d-11ea-84ac-0f8c6051b3a3.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/86563791-b3f8f800-bf6d-11ea-8c4c-e012bf74c9f1.png)

**Comment by BONNe** [comment]
Hmm, the required entity is null.. weird...

hmm... I could add null-pointer protections in the loading process...

**Comment by BONNe** [comment]
Oh I got it :D

Pigmen changes in challenges.
I need to add migration from 1.15.2 to 1.16....

As in one challenge it uses PigMan and it set it to null, as pigman entity in 1.16 does not exists :D

**Comment by OverBrave** [comment]
🧷

**Comment by BONNe** [comment]
Fixed in latest snapshot build.
