### ISSUE TITLE
challenge owner reset

### ISSUE THREAD

**Issue by Bricec6** [BentoBoxWorld/Challenges#253]
#### Describe the bug
Hello there is a problem with resetting challenges, when a player owns an island and leaves, his challenges are reset, however if the player is only kicking from the island his challenges will remain.

yet I did put in the configuration 
reset-challenges: false

Thank you!

##### Output of `/bbox version` (Mandatory)

![image](https://user-images.githubusercontent.com/51750055/88905002-16d06d00-d256-11ea-941e-582a523753c7.png)

```

EDIT: If a player leaves the island his challenges are also reset.

**Comment by Bricec6** [comment]
up
config addons challenge:
https://pastebin.com/TZstJdWP

**Comment by BONNe** [comment]
Blocked by https://github.com/BentoBoxWorld/BentoBox/issues/1492
