### ISSUE TITLE
Addon not recognizing ecomony plugin installed

### ISSUE THREAD

**Issue by teagan75** [BentoBoxWorld/Challenges#254]
**Description**
I am using several addons including Challenges (see below). I have installed latest version of Vault v1.7.3 and XConomy v2.5.9 but your addons that use money are not recognizing the plugins are installed. I can't see a place to link in configs.

![2020-08-06_14 42 59](https://user-images.githubusercontent.com/12485764/89575496-78af4a80-d7f3-11ea-9d44-ad4946bfcae8.png)

**Steps to reproduce the behavior:**
1. Install BSkyBlock, Challenges. Install the above versions of vault and xconomy.
2. Start server
3. See error in log
4. 06.08 15:19:33 [Server] Server thread/INFO [BentoBox] Enabling Challenges...
06.08 15:19:33 [Server] Server thread/INFO [BentoBox] [Challenges] Loading challenges...
06.08 15:19:36 [Server] Server thread/WARN [BentoBox] [Challenges] Economy plugin not found so money options will not work!

#### Expected behavior
Since there is built in support for vault I expected it to recognize it

##### Output of `/bbox version` (Mandatory)

```
06.08 15:32:42 [Server] Server thread/INFO Running SPIGOT 1.16.1.
06.08 15:32:42 [Server] Server thread/INFO BentoBox version: 1.14.2
06.08 15:32:42 [Server] Server thread/INFO Database: JSON
06.08 15:32:42 [Server] Server thread/INFO Loaded Game Worlds:
06.08 15:32:42 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
06.08 15:32:42 [Server] Server thread/INFO Loaded Addons:
06.08 15:32:42 [Server] Server thread/INFO BSkyBlock 1.13.1 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Challenges 0.8.3 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Chat 1.0.4 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO ExtraMobs 1.11.0.3 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Greenhouses 1.2.0-SNAPSHOT-b242 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Level 2.3.3 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Limits 1.14.0 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO MagicCobblestoneGenerator 2.0.0 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO TwerkingForTrees 1.4.1 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Upgrades 0.2.0-SNAPSHOT-b62 (ENABLED)
06.08 15:32:42 [Server] Server thread/INFO Warps 1.9.7 (ENABLED)
```

#### Plugins (Optional)

```
06.08 15:33:59 [Server] Server thread/INFO Plugins (4): Vault, BentoBox, PlayerKits, XConomy
```
 
### Additional context (Optional)
Vault version 1.7.3-b131
XConomy version 2.5.9
PlayerKits version 2.6.2

**Comment by BONNe** [comment]
I tried with XConomy-2.5.11 and for me, everything works.

**Comment by teagan75** [comment]
downloaded xconomy 2.5.11 and it still is erroring. Server says it is installed

**Comment by BONNe** [comment]
That is weird...
I cannot reproduce it at all. For me, everything works...

Hmm, I am using default xconomy config file. Have you made changes to it?

**Comment by teagan75** [comment]
No. I haven't made any changes. I am using a spigot jar from June 24 and I am wondering if I need to get a more recent one

**Comment by BONNe** [comment]
To be clear, this is not related to BentoBox or Challenges addons. We just check if the Economy is defined by Vault, and send a message, if it is not.

I checked on my test server and it worked, so it could be either your outdated spigot version or probably XConomy plugin is not working properly. For both issues, you should ask help from the plugin developer.

In their GitHub I saw the same report from another user, however it was closed without any proper answer from a developer side.

**Comment by teagan75** [comment]
Updating spigot did not work. I do not see the issue I am having on the other plugins issue trackers. Vault is loaded. So is Xconomy. Vault recognizes Xconomy like you can see in the above screenshot. There are no errors from those two plugins. Bento Box is not seeing Vault. 
![spigot version](https://user-images.githubusercontent.com/12485764/89666093-625ec880-d89f-11ea-89d2-c4b8cdf4de51.PNG)
