### ISSUE TITLE
Iron age challenge can not be completed if items have lore/nbt data (doesnt recognize items)

### ISSUE THREAD

**Issue by cloakfox** [BentoBoxWorld/Challenges#261]
#### Describe the bug
As the title says
#### Steps to reproduce the behavior
Try to complete iron age challenge with iron tools that have nbt data or lore

#### Expected behavior
To complete the challenge like normal

#### Screenshots and videos (Optional)
x

### Environment
x

#### Plugins (Optional)
GearSignature
### Additional context (Optional)
Apologies but I wont bother supplying all this data for such a simple bug.

**Comment by BONNe** [comment]
Items are compared with equal NBT data. If GearSignature adds some unique ID to each gear, it is not possible to compare them.

This would require accepting all items without checking for NBT, but it would mean that you cannot create a challenge that requires renamed item.
