### ISSUE TITLE
Sync data load from database on challenges command

### ISSUE THREAD

**Issue by sgdc3** [BentoBoxWorld/Challenges#263]
![Cattura](https://user-images.githubusercontent.com/8779252/100134414-7814ef80-2e88-11eb-819d-c3ef279e0267.PNG)
Using latest Challenges/Bentobox builds on Paper 1.16.3. Detected using [spark](https://github.com/lucko/spark)'s sampler.

**Comment by BONNe** [comment]
Oh.. yes :D 

I forgot to change that. Will do it.
