### ISSUE TITLE
BSkyblock with Challenges, challenges competent island gives error

### ISSUE THREAD

**Issue by KvasirQc** [BentoBoxWorld/Challenges#266]
Thanks for the nice plugiin. 

When trying to click on the Challenges competent island in Bskyblock, we receive the error "cannot complete challenge required addon or plugin is missing"

##### Output of `/bbox version` (Mandatory)

```
Running Paper 1.16.4
Bentobox version 1.15.2
Database JSON
bskyblock_world (BSkyblock): Overworld, nether, the end
skygrid-world (SkyGrid): Overworld, Nether, The End
Loaded addons
BSkyblock 1.14.3(Enabled)
Challenges 0.8.3(Enabled)
IslandFly 1.7.3(Enabled)
Skygrid 1.14.1 (Enabled)
_______
```

#### Plugins (Optional)

```

I do however have an old version of the plugin  IridiumSkyblock


```
 
### Additional context (Optional)

If you don't know where the problem is from, is there anyway to bypass that? Thanks again!

**Comment by BONNe** [comment]
Competent challenge in default configuration has only one requirement: reach island level 20.
However, you do not use level addon, so challenge complains that it cannot fulfill requirements to complete.

You can remove that challenge from the challenge list, as well as some others that also have only level requirement.

**Comment by KvasirQc** [comment]
Thank you, I wasn't aware of this level plugin :) Have a good evening
