### ISSUE TITLE
YML Storage for Challenges

### ISSUE THREAD

**Issue by Erorserv** [BentoBoxWorld/Challenges#267]
#### Is your feature request related to a problem?
No, rather a quality of life improvement.

#### Describe the solution you'd like us to implement.
Please allow for the individual challenge configs to be stored and read in YAML format. This would allow for quick and easy edit of multiple challenges, far quicker and more efficient than through the GUI. Reading JSON is straining on the eyes and risks syntax errors far more than YAML.

This isn't a particularly necessary change but it will make configuring a whole lot easier.

**Comment by BONNe** [comment]
Challenges will not be stored in YAML because BentoBox does not support the YAML database format.
