### ISSUE TITLE
Cycle Through Challenges as Pages

### ISSUE THREAD

**Issue by CodfishBender** [BentoBoxWorld/Challenges#268]
#### Describe the solution you'd like us to implement.
When there are more than 18 challenges in a a level, you are required to click "next" to scroll through the listings.
Please allow this to change to a page format so it displays the first 18 challenges, then the next 18 challenges instead of having to scroll through 1 by 1.

#### Describe alternatives you've considered.
I have tried creating more levels to spread out the challenges, but I end up running into the same issue when there are more than 9 levels and challenges become very disorganized.

**Comment by BONNe** [comment]
Implemented in 1.0 version after GUI's rework.
