### ISSUE TITLE
Do not show completed times if locale string is blank

### ISSUE THREAD

**Issue by Bs1D** [BentoBoxWorld/Challenges#280]
Hi while translating challenges 0.8.4 from locales folder, I have encountered an error which when I set something to [] for example:
"completed-times-of: []", the line at the lore doesnt dissappear but instead it shows some weird code in game. How can I fix this?

**Comment by tastybento** [comment]
The original line is:
```
completed-times-of: 'Completed [donetimes] out of [maxtimes]'
```

If you want to make that nothing, then do this:

```
completed-times-of: ''
```

That's two apostrophies.

**Comment by Bs1D** [comment]
Yes but I'd like to disable the line completely, when I try the thing you told me there are spaces between lines which looks bad in my opinion.

**Comment by tastybento** [comment]
That will require a code change. I’ll change this to a feature request.

**Comment by BONNe** [comment]
Will not implement.

There is already option to disable parts of the lore message via addon config.

Completion number relates to COUNT section.
