### ISSUE TITLE
Shift-click to complete multiple times

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/Challenges#281]
### Description
In challenges, you can setup a challenge that can be completed multiple times. It would be nice if players could SHIFT-click the challenge to complete it as many times, as they have enough items in their inventory. That would make it easier for players (actually they are the ones that want this feature), cuz they wont have to click it multiple times to complete the challenge.

#### Describe the solution you'd like us to implement.
Add SHIFT-click option for challenges, that can be completed multiple times.

### Additional context
Usefull for challenges where you can for example get 1 sand for 64 cactus - players built huge farms, but it takes long to convert cactuses to sand

**Comment by BONNe** [comment]
Currently, there is a Multiple-Completion GUI that opens when right-clicking challenges.

However, I would like to implement similar options like in MCG, where admins could configure actions.

**Comment by BONNe** [comment]
Since 1.0 Challenges addon has customizable GUI's, and the option to do such things.

The default GUI contains shift+click to complete the challenge as many times as possible.
