### ISSUE TITLE
Default cmd for (potion) effects is wrong?

### ISSUE THREAD

**Issue by L4BORG** [BentoBoxWorld/Challenges#288]
### Expected behavior

After completing challenges in one group potion effect should be applied to specific player.

### Observed/Actual behavior

No effects are applied, I assume it's because /effect command was changed?

### Steps/models to reproduce

Complete challenges in 1 group, ie novice.

### BentoBox version

[05:42:27 INFO]: BentoBox version 1.18.0

### Other

After importing default challenges BSkyBlock_advanced.json for example, would look like this:
``` 
 "rewardCommands": [
    "effect give [player] regeneration 600"
  ],
```

when it should look this (I think):
```
  "rewardCommands": [
    "effect [player] regeneration 600"
  ],
```

**Comment by BONNe** [comment]
Based on Minecraft Wiki:
https://minecraft.fandom.com/wiki/Commands/effect

**Comment by L4BORG** [comment]
Good point, didn't think of that. Maybe it would make sense to use /minecraft:effect as alternative?
