### ISSUE TITLE
New Challenges Layout Calculations

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#289]
### Expected behavior

Suffisticated compact layout:
Calculated required items by adding up all items to reduce number of lines seen by player
Page [number] placeholder calculation

### Observed/Actual behavior

The new challenges layout has some undesired side effects. In most cases, the gui is unreadable for players.

Screenshot of a challenge which requires multiple stacks:
![Screenshot_multiplestacks](https://user-images.githubusercontent.com/28690790/145803869-10c72c59-bbf3-4470-9483-aba857d03e63.png)

Screenshot of a challenge which requires multiple unstackable items:
![Screenshot_unstackable](https://user-images.githubusercontent.com/28690790/145803885-7ea96a86-1575-4955-a583-56ee6554ab3b.png)

Screenshot of the challenge menu with page [number]:
![Screenshot_pagenumber](https://user-images.githubusercontent.com/28690790/145803898-d8843837-66a6-4a7d-add9-cf985e531401.png)

### Steps/models to reproduce

Plain default test server.
Make new challenges with multiple items by bsbadmin challenges gui.
See result as a player
Quick example:
![Screenshot_testserver](https://user-images.githubusercontent.com/28690790/145805438-dcc7ea16-36b1-42a6-a0ce-86b897f9d79c.png)

### BentoBox version

Running PAPER Invalid.
BentoBox version: 1.18.1
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.14.1-SNAPSHOT-b210 (ENABLED)
BSkyBlock 1.15.2-SNAPSHOT-b716 (ENABLED)
Challenges 1.0.0-SNAPSHOT-b473 (ENABLED)
Level 2.8.1 (ENABLED)
Limits 1.18.1-SNAPSHOT-b277 (ENABLED)
MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b232 (ENABLED)
Warps 1.11.2-SNAPSHOT-b315 (ENABLED)

**Comment by BONNe** [comment]
Auto-generated text will never be something that will fulfill all esthetics. Especially, if you have a lot of items in requirements/rewards. It is just not possible in general. Some people want to merge items, some do not... 

In these situations, I always suggest just writing custom reward/requirement text and removing auto-generated text. 
You can do it via the locales file:
https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/resources/locales/en-US.yml#L852-L994

**Comment by BONNe** [comment]
Sorry, I completely forgot. 

In 1.0 version I introduced a new option for each challenge: "Items with ignored MetaData"

This option allows specifying, which items can ignore metadata and which not per each challenge.
By doing this, players now can create a challenge where it requires any enchanted book, and another challenge, that requires a specific enchanted book. 

You can add ignored meta data items in the challenge edit panel by clicking on GREEN_SHULKER_BOX icon.

**Comment by x1p** [comment]
A challenge requiring 15 stacks of material would not fit in anyones gui.

> In these situations, I always suggest just writing custom reward/requirement text and removing auto-generated text.

This means that I have to rewrite 250+ challenges to add 2 descriptions to each challenge (1 for the required items and 1 for the reward). Although it's very extensive, it can be done but introduces a huge risk of making a mistake. And if done, every change  in requirements/rewards from that day forward requires another change in descriptions.
This might be a "solution" only if you start a new line of challenges. Not sooner than that am I upgrading.

**Comment by BONNe** [comment]
I mean, if you specify that item ignores metadata, it will be grouped like this:
![2022-01-04_21 30 03](https://user-images.githubusercontent.com/1344358/148113599-f8332346-d709-48dc-b39d-f683002a8bd1.png)
