### ISSUE TITLE
Compatibility with Levels Addon.

### ISSUE THREAD

**Issue by SkySwordMC** [BentoBoxWorld/Challenges#292]
### Expected behavior

 Validation upon completing a level related challenge.

### Observed/Actual behavior

You cannot complete Challenges related to the Level addons. When you try it just send this error : 
 
![2022-02-12_23 17 59](https://user-images.githubusercontent.com/99142553/153730379-4c4d5f9d-2056-40e9-9970-fba47c35cfc0.png)

It seems that the addon cannot detect other addons. I've tried using older version of Level and beta versions but it kept sending me the same error.

You may already be aware of this bug. If not you would probably have when testing.

### Steps/models to reproduce

Download the default template and try to complete a challenge related to the level of the island.

### BentoBox version

![2022-02-12_23 12 06](https://user-images.githubusercontent.com/99142553/153730421-f9b04d3b-f5d0-4e35-8e79-25e4f990a9f0.png)
![2022-02-12_23 12 08](https://user-images.githubusercontent.com/99142553/153730424-5035c30e-de51-48ea-a3e0-d1fa1bae8ce3.png)

### Plugin list

![2022-02-12_23 12 56](https://user-images.githubusercontent.com/99142553/153730454-e5f098b9-8dd6-438c-8dae-6ac2d16d12e4.png)

**Comment by BONNe** [comment]
Hmm, I cannot reproduce it.
Using the same Challenges addon version and Level addon version. Detection is picked up at the addon startup.
```[BentoBox] [Challenges] Challenges Addon hooked into Level addon.```

And I created a challenge that requires me to reach level 2 of island level. And I complete it without issues after reaching level 2. 

I have island level 10.
I tried:
- Challenge level 1 -> failed (not required island level error message)
- Challenge level 9 -> failed (not required island level error message)
- Challenge level 10 -> success
- Challenge level 11 -> success

Could you check if Challenges addon picked up Level addon at the startup?

**Comment by BONNe** [comment]
Oh, it looks like because Biomes Addon crashed in hooking in with Greenhouses addon, other addons did not run functions. 

@tastybento I think this may be a bug in BentoBox. If addon for any reason crashes (does not matter, valid or invalid crash) in `allLoaded()` call, other addons do not execute it.  

Also, it looks like PlAddons do not see Addons, which would be expected, because of the different classloader. At least that is what I susspect. 

In this case, it looks like the error is because Biomes is Pladdon but GreenHouses are still addon.

**Comment by BONNe** [comment]
I made a pull request in GreenHouses addon https://github.com/BentoBoxWorld/Greenhouses/pull/90.

As soon as it is fixed, everything should work.

**Comment by BONNe** [comment]
If you update Greenhouses issue should be solved.
