### ISSUE TITLE
Reward commands are not working

### ISSUE THREAD

**Issue by Desxiaofeng** [BentoBoxWorld/Challenges#293]
### Expected behavior

I'm an op in my server , and I try to call command 'seed' from player perspective with this addon . If it goes well, the server seed will appear in the chat bar.
But it doesn't work . I'm not sure whether there is something wrong in the addon or there is something wrong in my operation.
Can you give a detail example of reward commands . Notes and FAQ about this are too simple.

### Observed/Actual behavior

The command starts with `[SELF]` as notes say , but it does work.
I have try 
"- [SELF]seed"   
    --Unknown command. Type "/help" for help.
"- [SELF] seed"  
    --[BentoBox] [Challenges] There are no challenges set up in CraftWorld{name=bskyblock_world}!    //can not open gui
"-[SELF] seed"
    --[BentoBox] Problem executing command executed by player - skipping! [BentoBox] Command was : -[SELF] seed
"-[SELF]seed" 
    --[BentoBox] Problem executing command executed by player - skipping!     [BentoBox] Command was : -[SELF]seed

Not all tries are recorded but all tries are failed.

### Steps/models to reproduce

"- [SELF]seed"
"- [SELF] seed" 
"-[SELF] seed" 
"-[SELF]seed"
....

### BentoBox version

[01:31:51 INFO]: Running SPIGOT 1.17.1.
[01:31:51 INFO]: BentoBox version: 1.20.0
[01:31:51 INFO]: Database: JSON
[01:31:51 INFO]: Loaded Game Worlds:
[01:31:51 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[01:31:51 INFO]: Loaded Addons:
[01:31:51 INFO]: Bank 1.4.0 (ENABLED)
[01:31:51 INFO]: Biomes 1.14.0 (ENABLED)
[01:31:51 INFO]: BSkyBlock 1.15.2 (ENABLED)
[01:31:51 INFO]: Challenges 1.0.0-SNAPSHOT-b477 (ENABLED)
[01:31:51 INFO]: ControlPanel 1.13.0 (ENABLED)
[01:31:51 INFO]: ExtraMobs 1.12 (ENABLED)
[01:31:51 INFO]: Level 2.9.0 (ENABLED)
[01:31:51 INFO]: MagicCobblestoneGenerator 2.4.0 (ENABLED)
[01:31:51 INFO]: Visit 1.4.0 (ENABLED)
[01:31:51 INFO]: Warps 1.11.2 (ENABLED)

### Plugin list

Challenges-1.0.0-SNAPSHOT-b477.jar

**Comment by BONNe** [comment]
It is simple: `-` is the issue

Remove it and it should work...

Not sure from where did you find that you should add `-`.

**Comment by Desxiaofeng** [comment]
Actually I tried it too，but get the same result.
 And I did not add -. It was already there.
 You can find it in the file“template.yml” below:
      # Commands contains a list of commands that will be executed after player
      # completes a challenge.
      # If command starts with `[SELF]` it will indicate that player will execute this command.
      # The command supports [player] placeholder that will be replaced with a player name who
      # completed the challenge.
      # It is not necessary to writhe `/`.
      # This examples first command will force player to execute `/island` command,
      # While second command will run `/kill [player]` from the server console.
      commands:
        - island
        - kill [player]

It works when it is "- kill [player]" and "- deop [player]" , but fails when it includes "[SELF]".

**Comment by BONNe** [comment]
Well it is not a `"- kill"` but it `- kill`

And - in front of kill and island indicates that there is a list of commands. It is YAML file syntax.
As soon as you add `"` it breaks syntax. 

In the log/console you can see what bento box tried to execute:
`-[BentoBox] Problem executing command executed by player - skipping! [BentoBox] Command was : -[SELF] seed`

And it starts with the `-[SELF]`. And because of that `-` in front, it is not working.

**Comment by Desxiaofeng** [comment]
emmm...
I didn't  add " . I just use it to tell you what I typed.
Maybe I should tell you in this way:

commands:[SELF]seed
commands:[SELF] seed
commands: [SELF]seed
commands: [SELF] seed
commands:-[SELF]seed
commands:-[SELF] seed
commands:- [SELF]seed
commands:- [SELF] seed
commands: -[SELF]seed
commands: -[SELF] seed
commands: - [SELF]seed
commands: - [SELF] seed
commands: 
-[SELF]seed
commands: 
-[SELF] seed
commands: 
- [SELF]seed
commands: 
- [SELF] seed
commands: 
-[SELF]seed
- kill [player]
commands: 
-[SELF] seed
- kill [player]
commands: 
- [SELF]seed
- kill [player]
commands: 
- [SELF] seed
- kill [player]

I've tested almost everything above, even more, and none of them work.
Maybe you should test whether it works properly when it includes [SELF].
Or you can give me an example that includes [SELF] in the same form as above ,then I test it and give the result to you.

**Comment by BONNe** [comment]
```
###########################################################################################
# This is a YML file. Be careful when editing. Check your edits in a YAML checker like    #
# the one at http://yaml-online-parser.appspot.com                                        #
###########################################################################################
# This is a template file that allows to create challenges in YAML format.
# Be aware, some features are not supported in YAML so some things may not be able to do with this
# file.
# Note that this is just a template. All challenges are stored and taken from the database.
# Template is used just for importing challenges in gamemode.
# Information about setup for the Template File are available at:
# https://docs.bentobox.world/en/latest/addons/Challenges/
challenges:
  # Each challenge starts withs it ID.
  # Everything for challenge must be inside it.
  example_inventory_challenge:
    # Name of the Challenge. If it is not present, name will be set to the challenge id.
    # Supports ColorCodes.
    name: "&2 Example Inventory Challenge"
    # Icon for the Challenge
    # It uses BentoBox ItemParser.
    # Write format can be found in: https://docs.bentobox.world/en/latest/BentoBox/ItemParser/
    icon: CHEST
    # Each challenge can have an extra text in their lore that is only for this challenge.
    # Text has its own Color Codes.
    description: |-
      &7 Description of inventory
      &7 challenge
    # This allows to set that challenge is completable by players. If challenge is not
    # deployed, then players cannot complete it until deployed status is set to true.
    deployed: true
    # This allows to set the ordering of the challenges inside same level.
    # If 2 challenges has the same order number, they will be ordered by their unique_id.
    order: 0
    # You can set that challenge is limited to a specific environment. Or leave it empty
    # as it will indicate that challenge can be completed in every dimension.
    # Supported values: NORMAL, NETHER, THE_END.
    environments:
      - NORMAL
      - NETHER
      - THE_END
    # This option allows to auto-hide challenge after player completes it.
    # It does not work for infinitely repeatable challenges.
    remove-completed: false
    # Type of the Challenge allows defining which requirements will be used.
    # Challenge cannot exist without type or requirements.
    # Each requirement has its own set of rules.
    # Currently, addon has 4 types:
    #    INVENTORY_TYPE - checks items in player inventory.
    #    ISLAND_TYPE - checks for blocks or entities on player island.
    #    OTHER_TYPE - checks different things like, experience, island level, balance.
    #    STATISTIC_TYPE - checks specific player statistic value.
    type: INVENTORY_TYPE
    # Requirements are the section that defines what challenge will require to do.
    requirements:
      # Take items allows to set that items will be removed from player inventory
      # after challenge completion.
      take-items: true
      items:
        - DIRT:2
    # Rewards section allows defining what player will receive after completing challenge
    # for the first time.
    rewards:
      # The reward text is a message in challenge "lore" that will be specific for
      # this challenge.
      text: "&7 Some Reward Text"
      # Items contains a list of rewards that player will receive.
      # It uses BentoBox ItemParser.
      # Write format can be found in: https://docs.bentobox.world/en/latest/BentoBox/ItemParser/
      items:
        - STONE:6
      # Experience allows defining player experience that he will receive for
      # completing the challenge.
      experience: 5
      # Money allows defining player money that he will receive for
      # completing the challenge.
      money: 1.6
      # Commands contains a list of commands that will be executed after player
      # completes a challenge.
      # If command starts with `[SELF]` it will indicate that player will execute this command.
      # The command supports [player] placeholder that will be replaced with a player name who
      # completed the challenge.
      # It is not necessary to writhe `/`.
      # This examples first command will force player to execute `/island` command,
      # While second command will run `/kill [player]` from the server console.
      commands:
        - "[SELF] say See... it works? Or is it not? Did it appear in chat?"
    # Repeatable allows to define if challenge is repeatable or not.
    # Repeat Rewards are stored only if repeatable is set to true.
    repeatable: false
levels:
  # Levels also must contain level-id as a name.
  example_level:
    # Name of the level. If it is not present, name will be set to the level id.
    # Supports ColorCodes.
    name: "&2 Example Level"
    # Icon for the Level. Will be displayed only for unlocked levels.
    # It uses BentoBox ItemParser.
    # Write format can be found in: https://docs.bentobox.world/en/latest/BentoBox/ItemParser/
    icon: BOOK
    # Locked level icon. Will be displayed if level is locked.
    # It uses BentoBox ItemParser.
    # Write format can be found in: https://docs.bentobox.world/en/latest/BentoBox/ItemParser/
    locked-icon: BOOK
    # Each level can have an extra text in their lore that is only for this level.
    # Text has its own Color Codes.
    description: |-
      &7 Description of Level
    # This allows to set the ordering for levels.
    # If 2 level has the same order number, they will be ordered by their unique_id.
    order: 1
    # This allows to set the how many challenges can be skipped to unlock next level.
    # This will not affect level completion status. Players will still need complete
    # every challenge to receive rewards.
    waiver: 1
    # Rewards section allows defining what player will receive after completing challenge
    # for the first time.
    rewards:
      # The reward text is a message in challenge "lore" that will be specific for
      # this challenge.
      text: "&7 Some Reward Text"
      # Items contains a list of rewards that player will receive.
      # It uses BentoBox ItemParser.
      # Write format can be found in: https://docs.bentobox.world/en/latest/BentoBox/ItemParser/
      items:
        - STONE:6
      # Experience allows defining player experience that he will receive for
      # completing the challenge.
      experience: 5
      # Money allows defining player money that he will receive for
      # completing the challenge.
      money: 1.6
      # Commands contains a list of commands that will be executed after player
      # completes a challenge.
      # If command starts with `[SELF]` it will indicate that player will execute this command.
      # The command supports [player] placeholder that will be replaced with a player name who
      # completed the challenge.
      # It is not necessary to writhe `/`.
      # This examples first command will force player to execute `/island` command,
      # While second command will run `/kill [player]` from the server console.
      commands:
        - island
        - kill [player]
    # Allows to define the list of challenges that will be linked to this level.
    challenges:
      - example_inventory_challenge
```

**Comment by BONNe** [comment]
The commands should be:
```
      commands:
        - "[SELF] say See... it works? Or is it not? Did it appear in chat?"
        - seed
        - "[SELF] seed"
    ```
In YAML syntax `-` at the start indicates next line is a list starting.
`[` and `]` are syntax symbols in yaml and that is the reason why you need `"` to surround text input, as otherwise, it would try to parse things in-between `[]` as an array. 

These are YAML syntax things. If you are not familiar with them, I suggest using in-game Admin GUI to create challenges. GUI allows to create everything for challenges without necessity to know any file format features.

**Comment by Desxiaofeng** [comment]
it works! It is amazing. 
Thank you.
And I suggest  that you note these in the wiki page .
