### ISSUE TITLE
Complete the challenge at the maximum

### ISSUE THREAD

**Issue by PapiCapi** [BentoBoxWorld/Challenges#294]
### Is your feature request related to a problem?

No, just quality of life.

### Describe the solution you'd like.

In the panel where players can increase or reduce the amount of challenge they are going to complete, it would be nice to have an option to complte the challenge as much as possible.
To do that, you would need to either increase the size of the inventory to put a new item or "just" add a right click listener on the complete button. If the player right clicks, then complete as much as possible.

### Describe alternatives you've considered.

The only alternatives are to spam the button of +5.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
This feature is implemented in 2.0

But due to the fact, that currently it is stuck in review, 2.0 is not released.
You can find it in the dev branch.

https://ci.codemc.io/job/BentoBoxWorld/job/Challenges/
