### ISSUE TITLE
lore-length not working

### ISSUE THREAD

**Issue by Tackoozle** [BentoBoxWorld/Challenges#297]
### Expected behavior

imo, when you set the lore-length to 25 (default), the lore should be cut, and set to the next line, after 25 chars. When the 26. char is in a word, continue that work and then split the line.

Also maybe i use it wrong?:D

### Observed/Actual behavior

lore-length does nothing to me. Set it to 40, 20, 2 - nothing changes

### Steps/models to reproduce

Screenshot of a challenge: https://i.imgur.com/oaIJ3wh.png
template: 
{
      "uniqueId": "Gut gerüstet",
      "friendlyName": "Gut gerüstet",
      "deployed": true,
      "description": [
        "Du räumst den Kleiderschrank auf und gibst ab: je eine komplette Dia-, Eisen-, Gold-, und Lederrüstung"
      ],
      "icon": "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_CHESTPLATE\n",
      "order": 2,
      "challengeType": "INVENTORY",
      "environment": [],
      "removeWhenCompleted": false,
      "level": "Meister",
      "requirements": {
        "class": "InventoryRequirements",
        "parameters": {
          "requiredItems": [
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_HELMET\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_CHESTPLATE\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_LEGGINGS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_BOOTS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: IRON_HELMET\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: IRON_CHESTPLATE\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: IRON_LEGGINGS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: IRON_BOOTS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: GOLDEN_HELMET\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: GOLDEN_CHESTPLATE\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: GOLDEN_LEGGINGS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: GOLDEN_BOOTS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: LEATHER_HELMET\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: LEATHER_CHESTPLATE\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: LEATHER_LEGGINGS\n",
            "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: LEATHER_BOOTS\n"
          ],
          "takeItems": true,
          "requiredPermissions": []
        }
      },
      "requiredPermissions": [],
      "requiredBlocks": {},
      "removeBlocks": false,
      "requiredEntities": {},
      "removeEntities": false,
      "requiredItems": [],
      "takeItems": true,
      "requiredExperience": 0,
      "takeExperience": false,
      "requiredMoney": 0,
      "takeMoney": false,
      "requiredIslandLevel": 0,
      "searchRadius": 10,
      "rewardText": "",
      "rewardItems": [
        "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: DIAMOND_HORSE_ARMOR\n",
        "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: CHAINMAIL_CHESTPLATE\n"
      ],
      "rewardExperience": 0,
      "rewardMoney": 0,
      "rewardCommands": [],
      "repeatable": true,
      "repeatRewardText": "",
      "maxTimes": 10,
      "repeatExperienceReward": 0,
      "repeatItemReward": [
        "is:\n  ==: org.bukkit.inventory.ItemStack\n  v: 2580\n  type: GOLDEN_HORSE_ARMOR\n"
      ],
      "repeatMoneyReward": 0,
      "repeatRewardCommands": []
    },

### BentoBox version

> bbox version
[07:12:56 INFO]: Ausführen von PAPER 1.19.
[07:12:56 INFO]: BentoBox version: 1.21.0-SNAPSHOT-b2267
[07:12:56 INFO]: Datenbank: MARIADB
[07:12:56 INFO]: Geladene Spielewelten:
[07:12:56 INFO]: bskyblock_world (bskyblock): Oberwelt, Nether, End
[07:12:56 INFO]: Geladene Addons:
[07:12:56 INFO]: Biomes 2.1.0-SNAPSHOT-b225 (ENABLED)
[07:12:56 INFO]: Border 4.0.0-SNAPSHOT-b141 (ENABLED)
[07:12:56 INFO]: BSkyBlock 1.15.2-SNAPSHOT-b718 (ENABLED)
[07:12:56 INFO]: Challenges 1.1.0-SNAPSHOT-b486 (ENABLED)
[07:12:56 INFO]: Level 2.9.1-SNAPSHOT-b505 (ENABLED)
[07:12:56 INFO]: Limits 1.19.1-SNAPSHOT-b295 (ENABLED)
[07:12:56 INFO]: MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b236 (ENABLED)
[07:12:56 INFO]: SkyblockUtils 1.2${build.number} (ENABLED)
[07:12:56 INFO]: Upgrades 0.2.0-SNAPSHOT-LOCAL (ENABLED)
[07:12:56 INFO]: Warps 1.13.0-SNAPSHOT-b325 (ENABLED)

**Comment by Tackoozle** [comment]
Well, i just noticed, thats this setting is not created on restart, if deleted..

**Comment by BONNe** [comment]
Lore length was removed due to request and impracticality in other languages.

You can change how long are challenges description each line manually when create a challenge
