### ISSUE TITLE
rewardCommands not accepting SELF

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Challenges#314]
### Expected behavior

A reward command like `[SELF] execute whatever` to be executed by the player itself

### Observed/Actual behavior

`Unknown command`

### Steps/models to reproduce

In order to narrow down what is actually happening I used the command `[SELF] list`

The console spits out:
```
[INFO]: [BentoBox] Running command '[SELF] list' as JackStillPlays
[ERROR]: [BentoBox] Problem executing command executed by player - skipping!
[ERROR]: [BentoBox] Command was : JckStillPlysist
```
Note that the executed command is completely garbled. The order of the characters are mixed.

### BentoBox version

Running PURPUR 1.19.3.
BentoBox version: 1.22.0-SNAPSHOT-b2328
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
BSkyBlock 1.17.0-SNAPSHOT-b724 (ENABLED)
Challenges 1.2.0-SNAPSHOT-b502 (ENABLED)
Level 2.10.0-SNAPSHOT-b521 (ENABLED)
Limits 1.19.1-SNAPSHOT-b301 (ENABLED)

**Comment by BONNe** [comment]
This issue has been fixed in the dev version b503
