### ISSUE TITLE
Make Undeployed Challenges not count for Level progress

### ISSUE THREAD

**Issue by Waterman1001** [BentoBoxWorld/Challenges#315]
### Is your feature request related to a problem?

Currently, levels can be configured such that if for example 2 challenges are not yet completed, then the player can still progress to the next stage (E.g. Expert Challenges).
However, this count is not updated if this level contains challenges that are not deployed.

For example:

The level 'Expert' is allowed to open if a player has still 2 challenges left to do from the 'Competent' stage.
The 'Competent' stage has 10 challenges associated with it.
Now, this means the player would need to complete 8 challenges in order to progress to the 'Expert' stage.
(Up to here, all fine! :D)
But now, one challenge in the 'Competent' stage is set to 'Undeployed' and it is also set to Hidden for players (nice functionality btw, amazing that this is possible!)
It would now be best if the 'Expert' stage would require the player to complete only 7 challenges from the 'Competent' stage in order to progress to it.
However, this unfortunately is not being done, and Undeployed challenges still count towards the Level Progress.

In worst case:
It would even be possible to UNDEPLOY multiple challenges, which makes that you can never achieve progress to the next level anymore. (E.g. It would say, you need to complete 8 more challenges, but since so many are undeployed, only 4 show up to the players)

### Describe the solution you'd like.

It would be nice if undeployed challenges are not counted as challenges that still need completion in order to progress to the next level. This would allow me to not forcefully have to DELETE challanges, but just make them UNDEPLOYED, allowing me to later make them available/release them again, e.g. in a Server Skyblock update.
Otherwise I have to delete challenges which I would like to somewhat keep for the future.

### Describe alternatives you've considered.

I have considered deleting challenges in order to achieve this, but in that case what is the point of undeploying challenges? 
I really really love the fact that I can mark challenges as undeployed, it is just a pity that this does not include the level progress calculation.
For me, I prefer undeploying rather than deleting challenges, as it keeps them in my database and I can always consider redeploying them. :D 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Thank you very much in advance for your understanding and for implementing this feature!
It would be great to have this! :)

**Comment by Waterman1001** [comment]
Update to this request:

It is also the case that if challenges are undeployed, and the player hovers with their mouse over a certain Level, it shows "Completed X out of Y challenges". Here, Y contains all challenges, instead of only Deployed challenges.

It would be nice if this also updates if `"undeployed-view-mode: HIDDEN"` is set.

**Comment by tastybento** [comment]
@BONNe This seems like a bug to me. I tried looking through the code, but I expect you know where to look. I'd say that the count for what still needs to be done needs revising to ignore hidden challenges. Do you agree?

**Comment by BONNe** [comment]
> @BONNe This seems like a bug to me. I tried looking through the code, but I expect you know where to look. I'd say that the count for what still needs to be done needs revising to ignore hidden challenges. Do you agree?

Yes and no...
Undeployed challenges are hidden only if the config option `undeployed-view-mode` is set to `hidden`.

I am working on adding a new option that would allow toggling for counting undeployed challenges in level too. 

Reasoning for the "toggleable" function and not using the view mode:
Players could complete levels while admins are working on new challenges, and get level rewards :) Not all servers want that.

**Comment by Waterman1001** [comment]
I am really glad to hear that my request is taken so seriously. Thank you so much already for this! 😇
