### ISSUE TITLE
[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### ISSUE THREAD

**Issue by hed516** [BentoBoxWorld/Challenges#319]
### Expected behavior

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### Observed/Actual behavior

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### Steps/models to reproduce

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

### BentoBox version

[BentoBox] Could not save object world.bentobox.challenges.database.object.Challenge Incorrect string value: '\xE6\x94\xB6\xE9\x9B\x86...' for column 'uniqueId' at row 1

**Comment by BONNe** [comment]
What name did you write for Challenge?

**Comment by tastybento** [comment]
Assume dupe of https://github.com/BentoBoxWorld/Biomes/issues/119
