### ISSUE TITLE
Bug challenges potions

### ISSUE THREAD

**Issue by Mundo-Minecraft** [BentoBoxWorld/Challenges#322]
### Expected behavior

There is a bug in the challenge plugin. 

### Observed/Actual behavior

In the Alchemist achievement it does not indicate which potions are needed, it just puts -potion. When I edit that achievement the required potions are correctly added.

### Steps/models to reproduce

You can see the error when reviewing the achievement itself.

[Image1](https://www.mundo-minecraft.com/wp-content/uploads/2023/07/2023-07-31_13.50.02.png)
[Image2](https://www.mundo-minecraft.com/wp-content/uploads/2023/07/2023-07-31_13.50.18.png)
[Image3](https://www.mundo-minecraft.com/wp-content/uploads/2023/07/2023-07-31_13.50.21.png)

### BentoBox version

BentoBox 1.24.1-SNAPSHOT-b2436
BSkyBlock 1.17.0-SNAPSHOT-b745
Challenges 1.3.0-SNAPSHOT-b531

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/resources/locales/en-US.yml#L1249-L1273

**Comment by Mundo-Minecraft** [comment]
Sorry I didn't see this report from 2022 https://github.com/BentoBoxWorld/Challenges/issues/290 it already works correctly and you can see the type of potions. Thank you for answering so quickly.
