### ISSUE TITLE
How to give an enchanted book a name？

### ISSUE THREAD

**Issue by Yukino12333** [BentoBoxWorld/Challenges#327]
### Is your feature request related to a problem?

I would like to change the name of each type of enchanted book in the challenge description; I know how to give an enchantment a name to an item, but the enchanted book will only show the name: 'Enchanted Book'

### Describe the solution you'd like.

Allow each enchanted book to display a specific name as if it were an enchantment for an item

### Describe alternatives you've considered.

I tried modifying the enchanted book in the same way that I changed the enchanted name of an item, but it didn't work

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

![image](https://github.com/BentoBoxWorld/Challenges/assets/99794710/4566afec-c0e0-428f-b763-cf6199dafb52)
![image](https://github.com/BentoBoxWorld/Challenges/assets/99794710/960ef48f-6e6d-4108-b620-a423bc359691)

**Comment by BONNe** [comment]
```
item-stacks:
   enchanted_book: "[enchant]"
```

**Comment by Yukino12333** [comment]
> ```
> item-stacks:
>    enchanted_book:
>       name: "[enchant]"
> ```

![image](https://github.com/BentoBoxWorld/Challenges/assets/99794710/d83cda17-f01c-4a6e-a6d7-9eb6c334f3eb)
Sorry, it still doesn't work with this configuration😭

**Comment by Yukino12333** [comment]
Please help me
