### ISSUE TITLE
Challenges isn't functional.

### ISSUE THREAD

**Issue by MagmaBro123** [BentoBoxWorld/Challenges#332]
### Expected behavior

Importing challenges to function.

### Observed/Actual behavior

The library button says lang entries are missing.

### Steps/models to reproduce

Try importing challenges.

### BentoBox version

![image](https://github.com/BentoBoxWorld/Challenges/assets/51277766/f5fb9b55-e22c-4d2b-8916-bf13457be7da)

### Plugin list

Tested with and without other plugins, same result.

### Other

N/A.

**Comment by BONNe** [comment]
Library relies on access to the GitHub. If you have disabled GitHub data pulling in be to box config, or your server has no access to the GitHub, then data will be empty.

Have you tried to import template or database?

**Comment by MagmaBro123** [comment]
> Library relies on access to the GitHub. If you have disabled GitHub data pulling in be to box config, or your server has no access to the GitHub, then data will be empty.
> 
> Have you tried to import template or database?

Never disabled Github data.

**Comment by MagmaBro123** [comment]
Apparently reimporting did fix the issue. Not sure why it was complaining about non-existent lang though.
