### ISSUE TITLE
Upgrade to Minecraft  1.20.4 and  BentoBox api 2.0 

### ISSUE THREAD

**Issue by BBDL233** [BentoBoxWorld/Challenges#336]
### Is your feature request related to a problem?

He has some issues in the higher version
He can work on 1.20.4, but cannot exit when entering challenge instructions

### Describe the solution you'd like.

Upgrade to Minecraft  1.20.4 and  BentoBox api 2.0 

### Describe alternatives you've considered.

He can work on 1.20.4, but cannot exit when entering challenge instructions

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Pending https://github.com/BentoBoxWorld/Challenges/pull/331

**Comment by tastybento** [comment]
Done with latest release.
