### ISSUE TITLE
Challenge info not showing correctly in the menu

### ISSUE THREAD

**Issue by Ritcheur** [BentoBoxWorld/Challenges#354]
### Expected behavior

In the menu, under the challenge's name, the values of its status, rewards or requirements sould be displayed.

### Observed/Actual behavior

Only the translated tag name is displayed. For exemple, "[récompenses]" (which stands for "rewards" in french) is displayed instead of the list of items, xp or money given to the player for completing the challenge.
![image](https://github.com/user-attachments/assets/963827bf-acca-4b52-ad62-fb4cf7d2d492)

The challenge levels are affected differently. While rewards etc. are displayed correctly, "[numéro]" (number) aren't. 
![image](https://github.com/user-attachments/assets/82482f3c-9066-4c86-b6b9-bf4d17d71469)

### Steps/models to reproduce

This happened after updating to Minecraft 1.21.1

### BentoBox version

En cours d'exécution PAPER 1.21.1.
(1.21.1-57-b483da4 (MC: 1.21.1))
Version de BentoBox : 2.5.3
Base de données : JSON2MARIADB
Mondes de Jeu Chargés :
bskyblock_world (BSkyBlock) : Overworld, Nether, The End
Addons Chargés :
Biomes 2.1.1 (ENABLED)
BSkyBlock 1.18.1 (ENABLED)
CauldronWitchery 2.1.0-SNAPSHOT-#62 (ENABLED)
Challenges 1.3.1 (ENABLED)
Chat 1.2.0 (ENABLED)
ControlPanel 1.13.1 (ENABLED)
DimensionalTrees 1.7.0 (ENABLED)
ExtraMobs 1.12 (ENABLED)
Greenhouses 1.8.0-SNAPSHOT-b372 (ENABLED)
Level 2.15.0 (ENABLED)
Limits 1.22.0 (ENABLED)
MagicCobblestoneGenerator 2.5.2-SNAPSHOT-b280 (ENABLED)
Upgrades 0.3.0-SNAPSHOT-b133 (ENABLED)
Warps 1.14.0 (ENABLED)

### Other

Our island level ranking doesn't work either. We have : "Rank: 1 - {papi:Level_bskyblock_top_name_1} with a level {papi:Level_bskublock_top_value_1} island"

Other addons, like Witchery, are showing information (such as wand prices or ingredients) correctly.

**Comment by tastybento** [comment]
This is because the tags for the locale have been translated. I'll try and fix now.

**Comment by tastybento** [comment]
I will do a release, but in the meantime you can download the updated French file:

https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/resources/locales/fr.yml
