### ISSUE TITLE
Island Challenges Range

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Challenges#4]
_From @Broanater on July 8, 2018 19:21_

**Is your feature request related to a problem? Please describe.**
When creating island challenges you are limited to a 10x10 area for ASkyblock.

**Describe the solution you'd like**
I would like there to be a config option to either change the size it checks, or to review the entire island.

_Copied from original issue: tastybento/bskyblock#198_

**Comment by BONNe** [comment]
Implemented
