### ISSUE TITLE
Give more importance and functionality to the end and the nether

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#42]
Give a purpose to the end and to the nether. Is there a possibility to go in the end and in the nether but for what purpose? Why should the player do it?
The player must be encouraged to go into the end and into the nether because that way he will get something useful. A very interesting idea would be to unlock new challenges dedicated to the end and the nether. So after entering for the first time in the end and in the nether I will unlock a new section of challenges dedicated to it and that I will be able to complete only in that world. In this way these two worlds will have a sense of existing. Bosses could also be implemented to be defeated in the two worlds, this seems to me very valid!

**Comment by tastybento** [comment]
Yes, I agree. The challenges add-on, in theory, does support the concept of world-specific challenges, but it needs to be developed.

**Comment by BONNe** [comment]
Nether is necessary for Blaze Rods... ghast tears and gold farm.
End is useful for enderpearl farm.

**Comment by BONNe** [comment]
Admins now can define challenges that could be done in specific environments.
