### ISSUE TITLE
Some /is challenges not working

### ISSUE THREAD

**Issue by Tobydj** [BentoBoxWorld/Challenges#43]
**Description**
When doing certain challenges such a the builder challenge it reports that I have to be island level of 10 even though I'm past is/level of 10

**Steps to reproduce the behavior:**
1. Create an island and build until your /is level is past 10
2. Do /is challenges and select the builder challenge.

**Expected behavior**
I expected to complete the challenge and receive the reward.

**Screenshots**
![screen shot 2018-12-19 at 17 22 46](https://user-images.githubusercontent.com/44133830/50233045-d5f25000-03b2-11e9-8036-dab6552d48f7.png)

**Server Information:**

[Please complete the following information:]
 - Flatfile
 - OS: iOS
 - Java Version: Java 8
 - BentoBox version: 0.16.0
 - Addons installed? BSkyBlock 0.5.0-SNAPSHOT, WelcomeWarps 0.1.0-SNAPSHOT, BentoBox-Challenges 0.0.3-SNAPSHOT, BentoBox-InvSwitcher 0.0.1-SNAPSHOT, Level 0.1.0-SNAPSHOT
 - Other plugins? CoreProtect, SketchMap, SubioCraftMenu, KeepItems, ShulkerBoxPackPacks, PlaceholderAPI, ClearLag, PlugMan, AutoMessage, CommandLog, Votifier, SilkSpawners, ProtocolLib, LibsDisguises, SkinsRestorer, VotingPlugin, FastAsyncWorldEdit, SignEdit, PermissionsEx, EffectLib, PartyAndFriendsGUI, mcMMO, DropEdit2, Vault, VentureChat, Essentials, LiteBans, BuycraftX, Citizens, ColoredTags, BentoBox, MysteryBoxes, PlayerVaults, SuperVanish, EssentialsSpawn, BungeeTabListPlus, Multiverse-Core, CitizensCMD, WarpSystem, UltimateShops, FrameProtect, WorldEdit, WorldGuard, Jobs

**Additional context**

**Comment by akoldfart** [comment]
At least "Builder" has that problem. Reported by player.

**Comment by Poslovitch** [comment]
@Tobydj and @akoldfart : Download [Challenges 0.3.0](https://github.com/BentoBoxWorld/Challenges/releases/tag/0.3.0) and [Level 0.2.0](https://github.com/BentoBoxWorld/Level/releases/tag/0.2.0). That should fix your problem.

**Comment by BONNe** [comment]
Fixed in latest snapshot build.
