### ISSUE TITLE
Challenges is not compilable

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Challenges#45]
I cannot compile Challenges anymore. I get a weird error about ambiguous async task, but it continues to exist even if I delete that line! I've traced it down to something in the commits from @Poslovitch over the last 2 days because before then, it compiles okay.

**Comment by BONNe** [comment]
Does it fail in `src/main/java/bentobox/addon/challenges/ChallengesManager.java:[394,45] reference to runTaskAsynchronously is ambiguous` ?

**Comment by BONNe** [comment]
So Build #49 failed because of SpigotApi changes in 1.13.2 for method runTaskAsynchronously 

BukkitSchefuler.runTaskAsynchronously(Plugin plugin, Consumer<BukkitTask> consumer) as second parameter now accepts only BukkitTask.

It can be easy fix in ChallengesManager.java line 394:
```java
            this.addon.getServer().getScheduler().runTaskAsynchronously(
                this.addon.getPlugin(),
                bukkitTask -> {
                    ChallengesManager.this.save();
                });
```

**Comment by tastybento** [comment]
Yes, thanks @BONNe . Actually, I don't want to do async saving here in this way. I think that async saving should be handled another way within BentoBox if we do it. So, for now, I'm removing this part anyway.
