### ISSUE TITLE
Order of challenges

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#46]
How come the challanges inside the gui do not come out in the order in which they were put in the config but in a random order? How can I solve this problem?

**Comment by tastybento** [comment]
Yes, the challenges appear in random order. You can manually specify which slot the challenge should be in by adjusting the specific challenge settings.

Go to the database folder (BentoBox/database/Challenges) and edit the files. Look for this line:

```
# Icon slot where this challenge should be placed. 0 to 49. A negative value means any slot
slot: -1
```

That's all there is right now until we have a GUI to allow reordering.

**Comment by Manu5656** [comment]
Okay, thank you

**Comment by BONNe** [comment]
Added option for challenges and levels so admins can use custom order. 
Option: order.
