### ISSUE TITLE
Money not updating users balance

### ISSUE THREAD

**Issue by MXR156** [BentoBoxWorld/Challenges#47]
**Description**
It appears that the Currnecy isn't tieing into the challenges quite right. I have been having to use eco give amount. The currency is also not being started the starting amount when the user starts a new island.

**Steps to reproduce the behavior:**
1. Go to 'Create New Island or complete a challenge and eco doesnt appear to be updating'

**Expected behavior**
Expecting this to tie into essentials vault and be able to add users money into balance.

**Screenshots**
Uploaded unlisted video to - https://youtu.be/TSI_R0HEtfE

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): YAML (I would like to use MySQL, but Back end is currently on MariaDB so will not connect)
 - OS: Unknown (Using ShockByte as host, Multicraft)
 - Java Version: Java 8
 - BentoBox Details: 
04.01 01:32:56 [Server] INFO Bentobox version: 0.17.0 
04.01 01:32:56 [Server] INFO Loaded Game Worlds: 
04.01 01:32:56 [Server] INFO Skylands (BSkyBlock) 
04.01 01:32:56 [Server] INFO Loaded Add-Ons 
04.01 01:32:56 [Server] INFO BSkyBlock 0.6.0 
04.01 01:32:56 [Server] INFO BentoBox-Challenges 0.0.3-SNAPSHOT 
04.01 01:32:56 [Server] INFO BentoBox-Level 0.0.2-SNAPSHOT 
04.01 01:32:56 [Server] INFO Biomes 0.3.0-SNAPSHOT 
04.01 01:32:56 [Server] INFO BentoBox-InvSwitcher 0.0.1-SNAPSHOT
 - Other plugins? [Do '/plugins' and copy/paste from the console]
04.01 01:34:18 [Server] INFO Plugins (21): LuckPerms, FastAsyncWorldEdit, LiteBansGUI, PlaceholderAPI, HolographicDisplays, Vault, SilkSpawners, Essentials, BentoBox, CustomOreGen, DeluxeMenus, Shop, SuperVanish, LiteBans, EssentialsSpawn, BungeeTabListPlus, DeluxeChat, TitleManager, WorldEdit, WorldGuard, ItemJoin

**Comment by BONNe** [comment]
Hi,
Challenges 0.0.3 - released version does not have implemented Economy.
But currently thats the only official release. 

I can suggest to use nightly build from development branch:
https://ci.codemc.org/job/BentoBoxWorld/job/Challenges/

**Comment by MXR156** [comment]
I will give it a go, Is this one tied into eco now? I will give it a try.

While I have the thread, does the /bsbadmin challenges commands work for removing users challenges?

**Comment by BONNe** [comment]
Do you mean resetting challenge for a user, or removing challenge from the list?

**Comment by MXR156** [comment]
Yeah, So that I can test the chalenge and remove it from myself after testing it with creative.

**Comment by MXR156** [comment]
Perfect, All seems to be working in the Development build :) Thanks!
