### ISSUE TITLE
Cactus Green Challenge not working

### ISSUE THREAD

**Issue by DerPatrick1987** [BentoBoxWorld/Challenges#48]
_**All Challenges wors so far, except the first one!**_

I do the challenge with the Cactus Green but it tells me that i don´t have enough, even tho i have had the exact amount, then a full stack and then a full inventory to test it. I even changed it to be ink sacks in the right folder.

1. Go to /is challenges
2. Click on Dye Maker
3. Chat gives me the following info: You do not have enough Cactus Green to complete this challenge!
4. No error in console

Expected behavior:
To do what it is supposed to like the other challenges...

Screenshots:
not needed i guess...

Server Information:
 - Database being used YAML
 - OS: Win10
 - Java Version: Java 8
 - BentoBox version: 1.0
 
Bentobox version: 1.0
Loaded Game Worlds:
BSkyBlock_world (BSkyBlock)
Loaded Add-Ons
BSkyBlock 1.0
Challenges 0.3.0
Level 0.2.0

Other plugins:

Plugins (69): CleanroomGenerator, PluginConstructorAPI, Notify, DoubleJump, AngelChest, SoundEvents, AntiCreeper, MinePacks, PlaceholderAPI, MultiInventory, PlugMan, SpawnJoin, NametagEdit, Poke, AutoRestart, ViaVersion, Jewels, LightAPI, CoreProtect, dynmap, LuckPerms, WorldEdit, HealthBar, GreatKits, ClearLag, CrackShot, Votifier, ProtocolLib, AdvancedPortals, ImageMaps, SerialKey, BlocksHub, InteractiveBooks, LumberJack, Vault, **KitPvP**, HolographicDisplays, WorldGuard, AntiPluginLookUp, Vote, AddLight, MaintenanceSpigot, WorldEditCUI, Essentials, Jobs, SalaryManager, BentoBox, EssentialsChat, Parkour, Lottery, ItemJoin, LastHolo, SuperVanish, CustomOreGen, EssentialsProtect, EssentialsSpawn, TitleManager, Multiverse-Core, Shopkeepers, DiscordSRV, AllDayAllNight, DeluxeHub, AdvancedRegionMarket, MobArena, FurnitureLib, CommandSigns, DiceFurniture, PluginLibrary, Autorank

Additional context:
KitPvP: Known to not handle the InventoryClickEvent correctly, so i disabled it!

**Comment by BONNe** [comment]
Have you change required items via admin gui for cactus green challenge?

**Comment by DerPatrick1987** [comment]
I tried, but I don´t understand how I would change the description/amount trough tge GUI. I try to edit the .yml now

**Comment by BONNe** [comment]
So, currently there is a bug, that occur if you edit items in challenge via GUI. After editing you cannot complete this challenge unless. you reimport challenges with overwrite mode or remove that challenge from database and import challenges without overwrite mode.

And via GUI you cannot change descriptions.

**Comment by tastybento** [comment]
@DerPatrick1987 Try the latest version of the addon.

**Comment by BONNe** [comment]
This should be fixed in latest snapshot version.
