### ISSUE TITLE
Changes made in challenges.yml don't take effect.

### ISSUE THREAD

**Issue by alexp9982** [BentoBoxWorld/Challenges#52]
**Description**
Any changes made in the challenges.yml file seem to do nothing. I've added several custom levels and challenges, but none of them managed to make it into the game.

**Steps to reproduce the behavior:**
1. Add a bunch of custom things to the Challenges.yml file
2. Watch none of them go into effect when you restart your server

**Expected behavior**
Changes made in the challenges.yml file to actually take effect.

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [YAML]
 - OS: [ANY]
 - Java Version: [Java 8]
 - BentoBox version: [1.0]
 - Addons installed? [
[INFO] Bentobox version: 1.0
[INFO] Loaded Game Worlds:
[INFO] BSkyBlock_world (BSkyBlock)
[INFO] Loaded Add-Ons
[INFO] BSkyBlock 1.0
[INFO] Challenges 0.3.0
[INFO] Level 0.2.0]
 - Other plugins? [[INFO] Plugins (56): PluginConstructorAPI, PlugMan, HolographicDisplays, ConsoleSpamFix, ezBroadcast, Arconix, FindBiome, NoteBlockAPI, TimeLockX, Commandspy, CratesPlus, JukeBox, LuckPerms, WorldEdit, SimpleStatsGui, ClearLag, CrackShot, BuycraftAnnouncer, SetSpawn, BuycraftX, Votifier, MVdWPlaceholderAPI, VotingPlugin, iDisguise, FakeOP, FeatherBoard, ConditionalCommands, Vault, MassiveCore, PerWorldInventory, PlotSquared, WorldGuard, Punishmental, KeepDeathDrop, Wild, Essentials, KitAdder, BentoBox, EssentialsChat, SuperVanish, ChestShop, CustomOreGen, Factions, EssentialsProtect, EssentialsGeoIP, ServerSigns, WorldGuardExtraFlags, FactionsFramework, Multiverse-Core, Multiverse-Portals, Multiverse-NetherPortals, Towny, EpicSpawners, ShopGUIPlus, PluginLibrary, Autorank]

**Additional context**
Our server is multiple gamemodes on one server, thats why there is all the other plugins and stuff.

**Comment by tastybento** [comment]
The Challenges plugin is still in development, but the challenges.yml is not used the same as ASkyBlock. It is for import only. If you are in AcidIsland, use the **/acid challenges import** command or **/acid challenges import overwrite** to import the file into the database. If you are in BSkyBlock use **/bsbadmin challenges import**.
