### ISSUE TITLE
Error while importing challenges

### ISSUE THREAD

**Issue by alexp9982** [BentoBoxWorld/Challenges#53]
**Description**
I don't quite know, have a look at the error:

```
29.01 15:48:33 [Server] WARN Unexpected exception while parsing console command "bsbadmin challenges import"
29.01 15:48:33 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'bsbadmin challenges import' in world.bentobox.bskyblock.commands.AdminCommand(bsbadmin)
29.01 15:48:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687) [custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
29.01 15:48:33 [Server] INFO Caused by: java.lang.NullPointerException
29.01 15:48:33 [Server] INFO at world.bentobox.challenges.FreshSqueezedChallenges.parseItems(FreshSqueezedChallenges.java:180) ~[?:?]
29.01 15:48:33 [Server] INFO at world.bentobox.challenges.FreshSqueezedChallenges.makeChallenges(FreshSqueezedChallenges.java:145) ~[?:?]
29.01 15:48:33 [Server] INFO at world.bentobox.challenges.FreshSqueezedChallenges.importChallenges(FreshSqueezedChallenges.java:67) ~[?:?]
29.01 15:48:33 [Server] INFO at world.bentobox.challenges.commands.admin.ImportCommand.execute(ImportCommand.java:26) ~[?:?]
29.01 15:48:33 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:243) ~[bentobox-1.2.0.jar:?]
29.01 15:48:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[custom-java8.jar:git-Spigot-f56e2e7-7fc66b2]
29.01 15:48:33 [Server] INFO ... 7 more
```

**Steps to reproduce the behavior:**
1. Type /bsbadmin challenges import

**Expected behavior**
I expected the challenges to be imported.

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML): []
 - OS: [ALL]
 - Java Version: [Java 8]
 - BentoBox version: [1.0]
 - Addons installed? [Challenges, Level, BSkyblock]
 - Other plugins? [None that would interfere]

**Additional context**

**Comment by tastybento** [comment]
The import is quite "brittle" and will break if there are unknown items in it. In this case, the error is being thrown due to a problem in a requiredItems: list. I can't say which one. I recommend you go back to what you edited and double check for any mistakes.

**Comment by alexp9982** [comment]
There was one error in the challenges.yml, but even after fixing it, the problem still occurs

**Comment by tastybento** [comment]
If this is still and issue we could have a look at it, but you'll need to supply your challenges.yml file so we can look at it (zip it and drag and drop here).

**Comment by alexp9982** [comment]
Do you have a discord I can send you the file in? I don't want anyone copying the custom challenges I wrote.

**Comment by BONNe** [comment]
https://discord.gg/B64JRK

**Comment by alexp9982** [comment]
EDIT to main post: I updated the error to the current error.

**Comment by tastybento** [comment]
Likely there's missing **itemReward** or **repeatItemReward** lines in the challenges.yml file for one or more of the challenges you made. The quickest way to fix this is to start with a working **challenges.yml** file and adjust or add the challenges carefully.

**Comment by tastybento** [comment]
The change I just committed will prevent an error from being thrown when importing the file if these kind of lines are missing from the challenges.yml file.
