### ISSUE TITLE
Per-island challenges

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/Challenges#55]
**Is your feature request related to a problem? Please describe.**
Currently challenges are per-player, each player has their own challenges they need to progress through - the problem with this is it can hurt the teamwork in island teams as it forces each player to progress through their own challenges

**Describe the solution you'd like**
Island challenges should be made per-island instead of per-player, what I mean by this is that instead of each player progressing through challenges on their own the challenge progression will be stored in the islands themselves. The team member that actually completes the challenge will be the one to receive the reward.

By default, only the island leader/owner should be able to be able to complete the challenges - but this can be changed via an island protection flag (should never allow visitors/coops/trusted to complete challenges, they cant open the GUI anyway) so that other island team members can complete the challenge and receive the reward.

All team members should always be able to open the challenges menu - the protection flag should only be able to control whether they can actually complete the challenge and claim the rewards or not.

Ideally this should lead to a system thats more team-friendly and means that team members will be working towards the same, or similar goals.

**Comment by BONNe** [comment]
Implemented in #-104 build.

**Comment by TheWranger** [comment]
@BONNe Do you want me to make another github ticket regarding the protection setting I mentioned (that controls who can complete challenges)?

**Comment by BONNe** [comment]
Yes :)
I forgot about that... Better create new one as custom flags is now a possibility in BentoBox :)
