### ISSUE TITLE
YML to MYSQL

### ISSUE THREAD

**Issue by baticag** [BentoBoxWorld/Challenges#58]
How to convert challenges from file YML database to MySQL database, since you now changed how they are saved in development build?

**Comment by baticag** [comment]
Challenges that are already imported and edited in separate files dont get
automaticly transfered to MySQL.

How to do that?

**Comment by BONNe** [comment]
Not sure if it is possible.  Need to ask @tastybento or @Poslovitch about database migrations.

**Comment by tastybento** [comment]
Sorry, this won't be supported. You'll need to recreate the challenges using the new version.

**Comment by BONNe** [comment]
Dont lie...
I am almost done with creating importer !!!

**Comment by tastybento** [comment]
Okay, well, if you can make it work. Thanks @BONNe !
