### ISSUE TITLE
New challenge type

### ISSUE THREAD

**Issue by Max2124** [BentoBoxWorld/Challenges#6]
In AskyBlock you can make challenge types like: level, island and inventory, but what I'm missing is a type like “hunting“ or something. My solution idea for this would be adding a Type called “hunting“ or “hunter“ wich allows you to make challenges where you have to kill a given amount of mobs or animals.

**Comment by BONNe** [comment]
Unforenenetely, due to the behaviour and construct of the addon, it is not possible to do it.
