### ISSUE TITLE
Upgrade to 0.5+

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Challenges#65]
Challenges Addon in 0.5.0 Snapshot was reworked, and fixed a lot of bugs. But it comes with cost. Old code was rewritten and upgrading from 0.3.0 is not an easy task.
This is a guide how to do it.

1. Stop server!
2. Create backup of your data.
3. Download latest Challenges 0.5.0+ version and put it in addons folder.
3*. Update locales folder.
4. Start your server.
5. As admin you should write `/bsb challenges` it will open GUI and click on Hopper that indicate that you want to import from previous Challenges version.
6. After import is done, stop the server.

And now comes the painful part. 
In Challenges 0.3 and bellow data storage was corrupted, as it duplicates world name in players challenge data. To restore players challenges data you must remove duplicate.

F.e. if your island world name is bskyblock, then in players data will be challenges: `bskyblockbskyblock_miner`.

**ATTENTION!!!!**
If server is not using YAML database type then Challenges 0.5 cannot be used until  ** BentoBox version 1.2.1**. BentoBox 1.2 and lower are not compatible with Challenges 0.5 data storing.

**Comment by tastybento** [comment]
I made a release here with these notes - https://github.com/BentoBoxWorld/Challenges/releases/tag/0.5.0
