### ISSUE TITLE
Only one row shown in player's challenges GUI when are 9 challenges in a level

### ISSUE THREAD

**Issue by Blatower21** [BentoBoxWorld/Challenges#68]
There is a bug in the challenges GUI when you have 9 challenges in a level. Example:
When you put 8 challenges in a level:
![8](https://user-images.githubusercontent.com/31895420/52146767-86ef3a00-2643-11e9-9c65-4cf7c0f7d2f1.jpg)
The Bug:When you put 9 challenges in a level:
![9](https://user-images.githubusercontent.com/31895420/52146882-d59cd400-2643-11e9-9669-97dc46ff3859.jpg)
When you put 10 challenges in a level:
![10](https://user-images.githubusercontent.com/31895420/52146899-e0efff80-2643-11e9-873e-2c0460ab5e84.png)

Version:
![version](https://user-images.githubusercontent.com/31895420/52146690-42fc3500-2643-11e9-800d-445893b67edb.jpg)

**Comment by BONNe** [comment]
Fixed in latest version.
