### ISSUE TITLE
where this my challanges ?

### ISSUE THREAD

**Issue by successed** [BentoBoxWorld/Challenges#69]
http://prntscr.com/mfw9h3

where this my challanges ?

bentabox version : http://prntscr.com/mfw8pc

server version http://prntscr.com/mfw8vl

**Comment by successed** [comment]
[Yeni WinRAR ZIP arşivi.zip](https://github.com/BentoBoxWorld/Challenges/files/2825143/Yeni.WinRAR.ZIP.arsivi.zip)

**Comment by tastybento** [comment]
Did you import them?

**Comment by BONNe** [comment]
That video is kinda out of date :(

https://github.com/BentoBoxWorld/Challenges/releases/tag/0.5.0

**Comment by successed** [comment]
I don't have time to try that right now.

**Comment by BONNe** [comment]
I will close this issue, as @successed is not giving an answer.
If you get this issue again, then you need to create new case.

**Comment by successed** [comment]
i don't care
