### ISSUE TITLE
Challenges Placeholders

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Challenges#74]
**Is your feature request related to a problem? Please describe.**
This feature request comes from #20.
Add different placeholders for challenges

**Describe the solution you'd like**
- [ ] ~Count of completed challenges~
- [ ] ~Count of completed levels~
- [ ] ~Last unlocked level~
- [ ] ~count of completed challenges per level - Hard to implement~
- [ ] ~completion count for each challenge - Hard to implement~

**Comment by BONNe** [comment]
This will be implemented in 0.6 release only if BentoBox will be released 1.3 till I will fix other issues.
As currently, Challenges addon will support only official releases.

**Comment by BONNe** [comment]
Postponed till later.

Currently, there is no way how to implement dynamic place-holders. Placeholders do not support removing and they must be registered in each game mode, that also complicates everything, as challenges and their level is created separately for each level.
It would be easier with RegEX, but PAPI is too stupid for that.

**Comment by BONNe** [comment]
There is now an ability to remove placeholders.
Partially will be implemented in 0.8.0 release.

**Comment by BONNe** [comment]
As placeholders are pretty stupid concept, I would like to implement only placeholders that will be used.
Please, write down placeholders you would like to be for challenges addon.

If there will be no requested placeholders, then I will not implement them at all.

**Comment by wellnesscookie** [comment]
%challenges_completed-ch_top-[number]%

%challenges_completed-ch_top_name-[number]%


%challenges_completed-level_top-[number]%

%challenges_completed-level_top_name-[number]%
[number] from 1-5 at least

**Comment by BONNe** [comment]
Could you explain what it should return?
As I do not get it from id's. (sorry)

**Comment by BONNe** [comment]
I will close this Issue case.
Any placeholder requests should be addressed via [Placeholder request](https://github.com/BentoBoxWorld/Challenges/issues/new?assignees=&labels=Type%3A+Enhancement&template=placeholder_request.md&title=Placeholder%3A+) issue template.
