### ISSUE TITLE
Incorrect text formatting

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Challenges#77]
**Description**
I have:
navigation: '&aClick para ver los retos del nivel &6[level]'

But then, it is splitted into two lines and only the first line have the color.

**Expected behavior**
To be able to show the message in just one line, since it looks more beautiful.

**Screenshots**
![bug](https://user-images.githubusercontent.com/13599841/52308917-e54b4e00-299e-11e9-8da7-9927ac911cd5.png)

**Comment by BONNe** [comment]
Fixed in latest snapshot.
