### ISSUE TITLE
"Necessary to have 0 on your account"

### ISSUE THREAD

**Issue by TheRealMakhulu** [BentoBoxWorld/Challenges#79]
**Description**
Whenever a player tries to complete a builder challenge such as the novice builder, they can't claim even if their level is well over 10. Error says "It is necessary to have 0 on your account to complete this challenge"

**Steps to reproduce the behavior:**
1. Go to island
2. Get island level 10 or above
3. Try to claim reward

**Expected behavior**
Player should be able to claim rewards and challenge.

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [YAML]
 - OS: [Windows 10]
 - Java Version: [Java 8]
 - BentoBox version: [1.2.1]
 - Addons installed? [BSkyblock 1.1, BentoBox 1.2.1, Challenges 0.5.0-SNAPSHOT, Biomes 0.4.1, Level 0.2.0]
 - Other plugins? [Addlight, BentoBox, Citizens, CompatNoCheatPlus, DiscordSRV, EssentialsX, GroupManager, HoloDisplays, KillerMoney, mcMMO, Multiverse Core, Multiverse NetherPortals, PerWorldInventory, PluginConstructorAPI, Plugman, ProtocolLib, PVPControl, Sentinel, ServerRestorer, Shopchest, SilkSpawners, SuperbVote, SupeTrails, TalkingBot, Vault, Votifier, Voting, Wild, WorldEdit, WorldGuard]

**Comment by BONNe** [comment]
This issue is fixed in snapshot 76
https://ci.codemc.org/job/BentoBoxWorld/job/Challenges/
