### ISSUE TITLE
Chinese player's wishes

### ISSUE THREAD

**Issue by jiumen** [BentoBoxWorld/Challenges#83]
Will you consider, will the Chinese mission file be?

**Comment by BONNe** [comment]
Did you mean translation file?

**Comment by jiumen** [comment]
I want the Chinese version of the task

**Comment by BONNe** [comment]
Sorry, I'm not an expert in the Chinese language, so someone should translate Challenges lang file.
And as there does not exist any Hard Codded strings (only for debug), there should not be any issue with it.

**Comment by Tdmy** [comment]
But I did not find the lang file

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Challenges/blob/master/src/main/resources/locales/en-US.yml

**Comment by Hagb** [comment]
Is there anyone working at the Chinese localization?
I plan to do that.

**Comment by Hagb** [comment]
#152

**Comment by Hagb** [comment]
#153
