### ISSUE TITLE
Challenges with dirt reward change dirt quantity after restart

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Challenges#84]
### Description
Challenges with dirt reward change dirt quantity after restart.

#### Steps to reproduce the behavior:

1. Set a challenge 4 stacks of dirt of reward
2. Restart the server
3. That challenge now has 8, 8, 8 and 8 of dirt instead of 64, 64, 64, 64

#### Server / BentoBox information:

Challenges 0.5.0
Database: yml

**Comment by BONNe** [comment]
How did you edit the challenge?
- You can edit challenges from admin GUI only.
   ** it is possible to edit while server is stopped, but only if you are using YAML or JSON database, and you should edit it in `BentoBox/Databases/Challenge/{world_name}_{challenge}.yaml`
And how did you restart the server?
- It is possible to lose data on hard reset. You should use stop command otherwise data can be lost.

**Comment by YellowZaki** [comment]
I did it from GUI.
Initially I imported them from challenges.yml and after restart all the dirt was messed so I edited them via GUI. But after a restart, again the same problem.
I have +100 challenges and only the dirt causes problem.

**Comment by BONNe** [comment]
This video shows how I am editing Rewards (requirements are the same).
https://www.youtube.com/watch?v=KyQhEqo_Mvc

Are you doing the same?
Could you create video, if it is possible?

**Comment by YellowZaki** [comment]
I do the same.
Try to place 3 stacks of dirt in the reward. Then restart and see.

**Comment by BONNe** [comment]
Done and everything worked. Did you press save?
Or at least tried to do the challenge?

**Comment by YellowZaki** [comment]
Yes I pressed save and my players did the challenge.
It is strange because 64 of dirt become to 8 of dirt.

**Comment by BONNe** [comment]
Could you upload here your dirt challenge?

**Comment by BONNe** [comment]
I found that this issue happens after BentoBox internal save call.

**Comment by BONNe** [comment]
Hi @YellowZaki,
Could you download 0.5.1 release and test if it works now for you without this issue?

**Comment by YellowZaki** [comment]
It seems to be fixed but I had to downgraded beacuse of https://github.com/BentoBoxWorld/Challenges/issues/91

**Comment by BONNe** [comment]
I will close, as it looks like the issue is solved.
If you encounter a new bug that looks similar to this one, please create a new issue.
