### ISSUE TITLE
History Log

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Challenges#90]
#### Is your feature request related to a problem?

Currently Challenges Addon has the ability to check when a challenge was done last time only. But it would be awesome if challenges addon could store complete history about a user. Also, after implementing #55, it could store also which user completes this challenge.

#### Describe the solution you'd like us to implement.

Ability to store complete history about challenges completion and reset.
As logs may become large, then admins should be able to purge these logs or disable their storing completely.

**Comment by Poslovitch** [comment]
You can use BentoBox's LogEntry for that ;)
Have a look at the Island `history`.

**Comment by BONNe** [comment]
Implemented in Build #107

**Comment by TheWranger** [comment]
Is there some way to make it so that log entries could get auto-deleted after a certain amount of days?
@BONNe

**Comment by BONNe** [comment]
Implement ability to set lifespan for history data (in days)
