### ISSUE TITLE
Locale messed up in 0.5.1

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Challenges#91]
### Description
Any locale is showed. I tried clearing the locale and the config to see if it was an error from upgrading but still happens.

#### Server / BentoBox information:
Challenges 0.5.1

#### Screenshots / Server log
![bugchall](https://user-images.githubusercontent.com/13599841/52865426-e3228580-313c-11e9-9c44-4f1e590fc966.png)

**Comment by BONNe** [comment]
You should update Lang file.
0.5.0 changes langs, so without update it will be wrong.
