### ISSUE TITLE
Use AddonRequestHandler to get completed/uncompleted challenges and ChallengeCompleteEvent

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Challenges#92]
I would like to be able to use the AddonRequestHandler to get the completed challenges and uncompleted challenges. 
See this if it helps: https://github.com/BentoBoxWorld/Level/blob/dfd9d3cb3df20efb043e95f07f0a6400e33d16d2/src/main/java/world/bentobox/level/requests/LevelRequestHandler.java

I also would like a ChallengeCompleteEvent.
See this if it helps: https://github.com/BentoBoxWorld/Level/blob/dfd9d3cb3df20efb043e95f07f0a6400e33d16d2/src/main/java/world/bentobox/level/calculators/PlayerLevel.java#L59

Thanks!

**Comment by BONNe** [comment]
@YellowZaki,
Is it necessary for an event to fire each time the user tries to complete a challenge, or only when a challenge is completed?

**Comment by YellowZaki** [comment]
Just on complete, so we can modify for example an scoreboard to show challenges completed, and uncompleted.

**Comment by BONNe** [comment]
Implemented the following events:
- ChallengeCompletedEvent: called when a user completes challenge;
- ChallengeResetAllEvent: called when all user challenges are reset;
- ChallengeResetEvent: called when a single user challenge is reset;
- LevelCompletedEvent: called when a level is completed.

Implemented the following request handlers:
- Challenge Data Request handler - returns data map about requested challenge;
- Level Data Request handler - returns data map about requested level;
- Challenge List Request handler - returns list of challenges that operates in requested world;
- Level List Request handler - returns list of levels that operates in requested world;
- Completed Challenges Request handler - returns set of completed challenges for requested user in requested world.

More explenations will be added in Wiki.
