### ISSUE TITLE
Per-island Challenges Protection Setting

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/Challenges#93]
#### Is your feature request related to a problem?

Island owners have no way of controlling who can complete island challenges and who can't.

#### Describe the solution you'd like us to implement.

A protection setting that island owners can use to control what ranks can complete island challenges. 

#### Additional context

The setting should ideally made so that it can't be possible to allow visitors and trusted users to complete challenges (since they can't even open the GUI), but I'm not sure if Bentobox's API allows for this.

**Comment by BONNe** [comment]
This will be implemented only if BentoBox will be released 1.3 till I will fix other issues.
As currently, Challenges addon will support only official releases.

**Comment by BONNe** [comment]
Implemented in snapshot #136
