### ISSUE TITLE
Unspecific meta

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#94]
### Description
You understand this better than I do. We already had an conversation on the discord.
Some items seem to bug the description, so you can see on: https://prnt.sc/mmfw4q .

#### Steps to reproduce the behavior:
1. Have a challenge that requires items like this one: http://prntscr.com/mmgkpk
2. You will see this: https://prnt.sc/mmfw4q

#### Server / BentoBox information:
```
Running PAPER 1.13.2.
BentoBox version: 1.3.0-SNAPSHOT
Loaded Game Worlds:
skyblock (skyblock)
Loaded Add-Ons
BSkyBlock 1.3.0-SNAPSHOT
WelcomeWarps 1.2-SNAPSHOT
Challenges 0.6.0-SNAPSHOT
Level 1.2.1-SNAPSHOT
Biomes 0.5.0-SNAPSHOT
SerbCraftAddon 2.0
```

#### Expected behavior / Additional context
Don't display so massive information on items that are not enchanted or so?

**Comment by BONNe** [comment]
There will be no changes that remove this meta, as it is a good way how to see if items are broken and challenges cannot be completed.

To fix it, you must remove this meta from an item. The easiest way how to do it is by replacing the item in the challenge with a new one.

In original Minecraft only enchanted or renamed items has Meta Data (except Maps and Fireworks). 
So if your item is with meta, users will not be able to complete a challenge, unless they could have access to items with the same metadata.

In 1.13 exist an easy way how to detect if an item has unnecessary meta without checking challenge description. F3 + H will display advanced tooltips in GUI and it will show NBT tags for all elements. So if your challenge has required items with NBT tag, then it may not work and should be replaced with an item, that does not have it. Off course, there exist exceptions like enchants, maps, fireworks, and others, but in most cases, be aware that NBT tag is not good for Required Elements in Challenges addons.
