### ISSUE TITLE
Challanges Protection Flag 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/Challenges#95]
### Description
A Protection flag to allow players to complate challabges while not in the island space.

Players should be able to complete challanges off there island zone, This would be usefull for say SkyGrid where i have it set that playes do not play in a island zone but are free to roam the map.

**Comment by BONNe** [comment]
Fast question about this fix implementation:
- Implement in Island GUI (#93 as this issue)
- Implement as boolean in each Challenge/Level
?

**Comment by robert-beckley** [comment]
Wait whats the question, i forgot where we are at with this.

In https://github.com/BentoBoxWorld/Challenges/issues/93 he wnats a normal flag where the island owner can do /is settings and toggle between visitor, member, ownwr. for if challanges can be done or not. (Witch is a good idea)

Im after a defualt flag setting to allow people to do challanges not on the grid when they have no island

**Comment by BONNe** [comment]
Ok... I will explain...
Should it be a World (GameMode) Flag or Specific challenge flag?

**Comment by robert-beckley** [comment]
I think a gamemode might be best so it would be in the {GAMEMODE} config.yml
![image](https://user-images.githubusercontent.com/41904721/52973535-7e07b200-3412-11e9-9a37-ffd5759dc134.png)

**Comment by BONNe** [comment]
On hold till BentoBox 1.3 Release

**Comment by BONNe** [comment]
Implemented in snapshot #136
