### ISSUE TITLE
Add a "save" button to the GUI

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Challenges#96]
#### Is your feature request related to a problem?
Users told me they tend to get mixed up with the "Import" button. They think it is a button that will import their newly created challenges into the gamemode. Thus, it's not the case, and they end up losing all their work.

#### Describe the solution you'd like us to implement.

Add a "Save" button to the Challenges edition GUI.

#### Describe alternatives you've considered.

Make clearer what the Import button actually does (add a descriptive description).

#### Additional context

None.

**Comment by BONNe** [comment]
![import03](https://user-images.githubusercontent.com/1344358/53148680-3325a000-35b4-11e9-973c-f665940674c8.png)
![importaskyblock](https://user-images.githubusercontent.com/1344358/53148682-33be3680-35b4-11e9-8d3e-5050b5a7ed1d.png)

Saving is done automatically. Save button will not be implemented.
