### ISSUE TITLE
Type reward commands in chat instead of using an Anvil GUI

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Challenges#97]
#### Is your feature request related to a problem?
An Anvil GUI looks great, but we can only type a limited amount of characters there. This is problematic when using permission plugins such as LuckPerms which tend to have very verbose commands.

#### Describe the solution you'd like us to implement.

Instead of typing reward commands in an Anvil GUI, type them in the chat (which as of a few versions have a nearly non-existent characters limit).

#### Describe alternatives you've considered.

None.

#### Additional context

None.

**Comment by BONNe** [comment]
Implemented in 158 build.
