### ISSUE TITLE
Add ability to define an icon for a locked level

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Challenges#98]
#### Is your feature request related to a problem?

Locked levels appear as books and this icon remains un-editable.

#### Describe the solution you'd like us to implement.

Add the ability to select an icon to display in case the level is locked.

#### Describe alternatives you've considered.

None.

#### Additional context

None.

**Comment by BONNe** [comment]
So, it is easy to implement, but I should now how do you want this to be:
- Single icon in config.yml that allows to change locked level icon.
- One more parameter in ChallengeLevel object that will be used if level is locked?

**Comment by Poslovitch** [comment]
Each level should have its own icon.

However, users may also want to chose the default locked level icon.

**Comment by BONNe** [comment]
Implemented in build #137
